### PR TITLE
Bugfix: Inline polymorphic operators

### LINKED ISSUE #1880: Type concretization for nullary expressions
The PR #1878 has surfaced a type concretization bug that was somehow avoiding the post type checker. Consider the following specification:

```tla
-------------------------- MODULE TestPolyNullary ------------------------------
EXTENDS FiniteSets

VARIABLES
    \* @type: Set(Int);
    set

Init ==
    LET \* @type: () => Set(a);
        Empty == {}
    IN
    set = Empty

Next == UNCHANGED set
================================================================================
```

When we run Apalache against #1878, the following bug occurs:

```
unexpected expression: Expected a non-polymorphic type, found: (() => Set(c))
```

This caused by the fact that the operator `Empty` is nullary and thus it remains polymorphic. We should concretize its type, as we are doing it for non-nullary operators.

### LINKED ISSUE #1885: Inliner: Unable to unify generic signature with the concrete type
## Description

I have created a stripped down version of the model to demonstrate the issue.
It seems that the concrete type of Num ((Int) => Int) does not match to its annotation ([cycle: Int, index: Int]) => Int),
and I don't understand why.

## Impact

I was not able to find a workaround, so I am unable to check my model.

## Input specification

```
-------------------------------- MODULE bug --------------------------------
EXTENDS Integers

\* @type: (Int) => Int;
Cycle(x) == x \div 2

\* @type: (Int, Int) => Int;
Add(x, y) == x + y

\* @type: ([index: Int, cycle: Int]) => Int;
Num(e) ==2 * e.cycle + e.index

\* @type: ([index: Int, cycle: Int], [index: Int, cycle: Int]) => Bool;
OneCycleAhead(x, y) == Cycle(Num(x)) = Cycle(Add(Num(y), 2))

Init == TRUE
Next == TRUE
=============================================================================
````

## The command line parameters used to run the tool

```
apalache-mc check bug.tla
```

## Log files

```
11:59:52.986 [main] INFO  a.f.a.t.Tool\$ - # APALACHE version: 0.25.7 | build: 554bdb5
11:59:53.174 [main] INFO  a.f.a.t.Tool\$ - Checker options: check bug.tla
11:59:53.176 [main] INFO  a.f.a.t.Tool\$ - Tuning:
11:59:53.178 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
11:59:53.388 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
11:59:53.389 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
11:59:53.389 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
11:59:53.590 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Your types are purrfect!
11:59:53.590 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > All expressions are typed
11:59:53.591 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [OK]
11:59:53.591 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass
11:59:53.596 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --init is not set. Using Init
11:59:53.596 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --next is not set. Using Next
11:59:53.596 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to Init
11:59:53.597 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
11:59:53.600 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass [OK]
11:59:53.601 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass
11:59:53.601 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
11:59:53.607 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass [OK]
11:59:53.607 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #4: InlinePass
11:59:53.608 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next
11:59:53.643 [main] ERROR a.f.a.t.Tool\$ - <unknown>: internal error in type checking: Inliner: Unable to unify generic signature (([cycle: Int, index: Int]) => Int) of Num with the concrete type ((Int) => Int)
at.forsyte.apalache.tla.lir.TypingException: Inliner: Unable to unify generic signature (([cycle: Int, index: Int]) => Int) of Num with the concrete type ((Int) => Int)
	at at.forsyte.apalache.tla.pp.Inliner.getSubstitution(Inliner.scala:98)
	at at.forsyte.apalache.tla.pp.Inliner.instantiateWithArgs(Inliner.scala:133)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:168)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:206)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at at.forsyte.apalache.tla.pp.Inliner.instantiateWithArgs(Inliner.scala:124)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:168)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:206)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at at.forsyte.apalache.tla.pp.Inliner.instantiateWithArgs(Inliner.scala:124)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:168)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at scala.collection.immutable.List.map(List.scala:250)
	at scala.collection.immutable.List.map(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$transform\$1(Inliner.scala:206)
	at at.forsyte.apalache.tla.lir.transformations.impl.TrackerWithListeners.\$anonfun\$trackEx\$1(TrackerWithListeners.scala:18)
	at at.forsyte.apalache.tla.pp.Inliner.\$anonfun\$pushDeclsIntoScope\$1(Inliner.scala:65)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.tla.pp.Inliner.pushDeclsIntoScope(Inliner.scala:61)
	at at.forsyte.apalache.tla.pp.Inliner.transformModule(Inliner.scala:224)
	at at.forsyte.apalache.tla.pp.passes.InlinePassImpl.execute(InlinePassImpl.scala:55)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec\$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$5(PassChainExecutor.scala:47)
	at scala.util.Either.flatMap(Either.scala:352)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.\$anonfun\$run\$3(PassChainExecutor.scala:46)
	at scala.collection.LinearSeqOps.foldLeft(LinearSeq.scala:169)
	at scala.collection.LinearSeqOps.foldLeft\$(LinearSeq.scala:165)
	at scala.collection.immutable.List.foldLeft(List.scala:79)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:41)
	at at.forsyte.apalache.tla.Tool\$.runAndExit(Tool.scala:193)
	at at.forsyte.apalache.tla.Tool\$.runCheck(Tool.scala:282)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$3(Tool.scala:136)
	at at.forsyte.apalache.tla.Tool\$.\$anonfun\$run\$3\$adapted(Tool.scala:136)
	at at.forsyte.apalache.tla.Tool\$.handleExceptions(Tool.scala:440)
	at at.forsyte.apalache.tla.Tool\$.runForModule(Tool.scala:430)
	at at.forsyte.apalache.tla.Tool\$.run(Tool.scala:136)
	at at.forsyte.apalache.tla.Tool\$.main(Tool.scala:48)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

## System information

- Apalache version: `0.25.7 build 554bdb5`:
- OS: `Linux`:
- JDK version: `17.0.3`:

### PR DESCRIPTION
**Pull request by Kukovec**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [x] Entries added to [./unreleased/][unreleased] for any new functionality

[unreleased]: https://github.com/informalsystems/apalache/tree/unstable/.unreleased

closes #1880 
Also closes #1885

### CODE REVIEW

File: tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala [hunk 1]
```diff
@@ -37,6 +39,22 @@ object TlaType1 {
       case _ => throw new TypingException("Expected Typed(_: TlaType1), found: " + typeTag, UID.nullId)
     }
   }
+
+  // returns true iff the type is a monotype, i.e. if it contains on type variables
+  def isMono(tt: TlaType1): Boolean = tt match {
+    case _: VarT1                 => false
```
Comment (shonfeder) [inline tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala:45]: Why doesn't this just using the constructor pattern match?

```suggestion
    case VarT1(_)                 => false
```

File: tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala [hunk 2]
```diff
@@ -37,6 +39,22 @@ object TlaType1 {
...
+    case SetT1(elem)              => isMono(elem)
+    case SeqT1(elem)              => isMono(elem)
+    case TupT1(elems @ _*)        => elems.forall(isMono)
+    case SparseTupT1(fieldTypes)  => fieldTypes.values.forall(isMono)
+    case RecT1(fieldTypes)        => fieldTypes.values.forall(isMono)
+    case OperT1(args, res)        => (res +: args).forall(isMono)
+    case RowT1(fieldTypes, other) => (other ++ fieldTypes.values).forall(isMono)
+    case RecRowT1(row)            => isMono(row)
+    case VariantT1(row)           => isMono(row)
+    case _                        => true
```
Comment (shonfeder) [inline tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala:56]: This will end up leading to false positives anytime a new constructor is added. Let's not have a wildcard match here, and instead require enumeration of all options?

```suggestion
```

**Review by shonfeder — CHANGES_REQUESTED** [review]

File: tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala (hunk 1 above)
Comment (Kukovec) [reply tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala:45]: Because they're semantically equivalent, but the `_: X` approach generalizes better with arity.

File: tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala (hunk 2 above)
Comment (Kukovec) [reply tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala:56]: How much of an issue is this really? We're not adding more types anytime soon, and besides, 95% of our matches have a default branch, because it avoids code duplication.

File: tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala (hunk 1 above)
Comment (shonfeder) [reply tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala:45]: Doesn't seem clear to me that the generalization helps with anything here, but fine with leaving it if you prefer.

File: tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala (hunk 2 above)
Comment (shonfeder) [reply tlair/src/main/scala/at/forsyte/apalache/tla/lir/TlaType1.scala:56]: This is a bug waiting to happen, and it will guarantee incorrect behavior, unless the person making the change explicitly writes a test for it. Meanwhile, iiuc, it should be trivially easy to ensure all the cases are enumerated, and statically guarantee this bug wont arise. So why not do it?

**Review by konnov — APPROVED** [review]
I think we are good to merge it!

**Review by shonfeder — APPROVED** [review]
