### PR TITLE
Fix stack overflow in the function constructor and OOM in oracles

### LINKED ISSUE #1483: Stack overflow due to non-tail recursion
Consider the following simple spec:

```tla
-------------------------- MODULE TestFunCtor ---------------------------------  
EXTENDS Integers

VARIABLES
    \* @type: Int -> Int;
    f

Init ==
    f = [ x \in 1..10000 |-> x ]

Next ==
    UNCHANGED f
===============================================================================
```

When I check this specification, it reports a stack overflow.

```sh
apalache-mc check TestFunCtor.tla
...
Unhandled exception
java.lang.StackOverflowError: null
	at at.forsyte.apalache.tla.bmcmt.rules.FunCtorRule.process$1(FunCtorRule.scala:109)
	at at.forsyte.apalache.tla.bmcmt.rules.FunCtorRule.process$1(FunCtorRule.scala:113)
...
```

We should refactor `FunCtorRule` to avoid this exception.

### PR DESCRIPTION
**Pull request by konnov**
Closes #1483. This PR fixes a stack overflow caused by non-tail recursion in the function constructor. After fixing this bug, I have found that the oracles are producing out of memory. This bug is also fixed.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

### CODE REVIEW

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala [hunk 1]
```diff
@@ -45,7 +45,8 @@ class SymbStateDecoder(solverContext: SolverContext, rewriter: SymbStateRewriter
       } else {
         // if not in the cache, it might be the case that another cell, which has asserted equivalence
         // with the original cell can be found
-        findCellInSet(rewriter.modelValueCache.values().toSeq, cell.toNameEx) match {
+        val values = rewriter.modelValueCache.values().filter(_.cellType == ConstT(uninterpretedType)).toSeq
+        findCellInSet(values, cell.toNameEx) match {
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala:49]: Why didn't we filter for `cellType` here before? I'm lacking context to understand this change.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala [hunk 2]
```diff
@@ -55,24 +55,37 @@ abstract class AbstractCache[ContextT, SourceT, TargetT]
     } else {
       // introduce a new constant
       val (newContext, targetValue) = create(context, srcValue)
-      cache = cache + (srcValue -> (targetValue, level))
-      reverseCache = reverseCache + (targetValue -> (srcValue, level))
+      addToCache(srcValue, targetValue)
+      cache += srcValue -> (targetValue, level)
+      reverseCache += targetValue -> (srcValue, level)
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:60]: This looks duplicate?

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala [hunk 3]
```diff
@@ -55,24 +55,37 @@ abstract class AbstractCache[ContextT, SourceT, TargetT]
...
       (newContext, targetValue)
     }
   }
 
+  /**
+   * Add a value to the cache. Implementations of this class may use this method for a more efficient mass construction
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:66]:
```suggestion
   * Add a value to the cache at the current level. Implementations of this class may use this method for a more efficient mass construction
```

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala [hunk 4]
```diff
@@ -55,24 +55,37 @@ abstract class AbstractCache[ContextT, SourceT, TargetT]
...
    *   a source value
    * @return
    *   Some(result), or None
    */
   def get(srcValue: SourceT): Option[TargetT] = {
-    cache.get(srcValue) match {
-      case Some((target, _)) => Some(target)
-      case None              => None
-    }
+    cache.get(srcValue).map(_._1)
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:88]: This looks like premature optimization, I find the previous version more readable.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ModelValueCache.scala [hunk 5]
```diff
@@ -22,15 +22,43 @@ class ModelValueCache(solverContext: SolverContext)
...
+    // The fresh cell should differ from the previously created cells.
+    // We use the SMT constraint (distinct ...).
+    val others = values().filter(_.cellType == ConstT(utype)).map(_.toNameEx).toSeq
+    solverContext.assertGroundExpr(OperEx(ApalacheOper.distinct, newCell.toNameEx +: others: _*))
     solverContext.log("; cached \"%s\" to %s".format(typeAndIndex, newCell))
     (newArena, newCell)
   }
+
+  /**
+   * Cache multiple values at once. This method is more efficient than caching multiple values with [[create]].
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ModelValueCache.scala:34]:
```suggestion
   * Create and cache multiple values at once. This method is more efficient than caching multiple values with [[create]].
```

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ModelValueCache.scala [hunk 6]
```diff
@@ -22,15 +22,43 @@ class ModelValueCache(solverContext: SolverContext)
...
+   *
+   * @param arena
+   *   the arena to start with
+   * @param utype
+   *   the value type
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ModelValueCache.scala:39]: value type of what?

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala [hunk 7]
```diff
@@ -57,7 +57,7 @@ class FunCtorRule(rewriter: SymbStateRewriter) extends RewritingRule {
       .typed(TupT1(funT1.arg, funT1.res))
 
     val (afterMapState: SymbState, relationCells: Seq[ArenaCell]) =
-      mapCells(nextState, pairEx, varName, setEx, domainCells)
+      mapCells(nextState, pairEx, varName, domainCells)
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:60]: As a general comment, I'd prefer to see refactorings in an incremental, separate commit. Much easier to review.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala [hunk 8]
```diff
@@ -101,28 +99,20 @@ class FunCtorRule(rewriter: SymbStateRewriter) extends RewritingRule {
...
 
-        case cell :: tail =>
-          val (ts: SymbState, nt: List[TlaEx]) = process(st, tail)
-          val newBinding = Binding(ts.binding.toMap + (varName -> cell))
-          val cellState = new SymbState(mapEx, ts.arena, newBinding)
-          // add [cell/x]
-          val ns = rewriter.rewriteUntilDone(cellState)
-          (ns.setBinding(ts.binding), ns.ex :: nt) // reset binding and add the new expression in the head
-      }
+    // similar to SymbStateRewriter.rewriteSeqUntilDone and SetFilterRule
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:105]: This comment could be improved. I don't know `rewriteSeqUntilDone` and `SetFilterRule`. Even if I did, what does "similar" mean in this context?

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala [hunk 9]
```diff
@@ -101,28 +99,20 @@ class FunCtorRule(rewriter: SymbStateRewriter) extends RewritingRule {
...
+      nextState.asCell
     }
 
     // compute mappings for all the cells (some of them may coincide, that's fine)
-    val (newState: SymbState, newEs: Seq[TlaEx]) = process(state, oldCells)
-    val newCells = newEs.map(newState.arena.findCellByNameEx)
+    val mappedCells = oldCells.map(mapOne)
     // keep the sequence of results as it is, as it is will be zipped by the function constructor
-    (newState, newCells)
+    (nextState.setBinding(state.binding), mappedCells)
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:116]: Can we make `nextState` immutable? I don't expect comprehensions to have side-effects.

**Review by thpani — COMMENTED** [review]
> This PR fixes a stack overflow caused by non-tail recursion in the function constructor. After fixing this bug, I have found that the oracles are producing out of memory. This bug is also fixed.

It would be helpful, for context, to know how these are fixed by the PR.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala (hunk 3 above)
Comment (thpani) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:66]: I'm also not sure I understand the second sentence. Nothing about this method per-se seems to make things more efficient?

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala (hunk 1 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala:49]: Looks like that was simply wrong. It was not updated after introducing model values.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala (hunk 2 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:60]: oh yes, good catch

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala (hunk 3 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:66]: It does call `distinct` over `n` arguments once, instead of introducing `n` calls to `distinct`.

Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:66]: I will add a comment

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala (hunk 4 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:88]: Interesting. This is not an optimization, but a shorter version of the same code :)

Comment (thpani) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala:88]: Right, optimising for short code 😉

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala (hunk 8 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:105]: Good point. This comment seems to be outdated. Removed.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala (hunk 9 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:116]: We can, but this will make the code much harder to read. We have this mix of mutable modifications to the state and the arena in many places, and it is significantly shorter and easier to read than the pure folds.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala (hunk 1 above)
Comment (thpani) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/SymbStateDecoder.scala:49]: SG

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala (hunk 9 above)
Comment (thpani) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:115]: But in this case you could just return the state of each step; then `nextState` is the tail of that `Seq` and you can `.map(_.asCell)` to get `newCells`?

Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:115]: ah, yes, this could work, unless the sequence is empty

Comment (thpani) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/FunCtorRule.scala:115]: But you're right, I missed the empty Seq corner case. Resolve this as you see fit!

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala (hunk 3 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/AbstractCache.scala]: Right. I have removed that other sentence. It is confusing.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ModelValueCache.scala (hunk 6 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/caches/ModelValueCache.scala]: Fixed: the name of the uninterpreted type to use

**Comment by konnov** [comment]
Can we merge this PR?

**Review by thpani — APPROVED** [review]
> Can we merge this PR?

I got lost in the changes on my last attempt, still had to check where the non-tail recursive call was and how it was fixed.

LGTM, up to `AbstractCache.get`. The old version is more readable, and I prefer readability over short code.

**Comment by konnov** [comment]
> > Can we merge this PR?
> 
> I got lost in the changes on my last attempt, still had to check where the non-tail recursive call was and how it was fixed.
> 
> LGTM, up to `AbstractCache.get`. The old version is more readable, and I prefer readability over short code.

Ok. I will rollback that one and merge
