### PR TITLE
Fixed handling of polymorphic operator types in folds

### LINKED ISSUE #1085: [BUG] Types are not propagated correctly when instantiating polymorphic operators that use folds
## Description

After instantiating a polymorphic operator, which uses a fold, the annotations that are propagated for the fold operator body are not correctly unified with the types derived from the operator arguments at the call site, resulting in the following error:
```
[test.tla:9:32-9:32]: Found a polymorphic type: (a79 -> Int)      E@18:24:28.109
Probable causes: an empty set { } needs a type annotation or an incorrect record field is used E@18:24:28.109
Typing input error: [test.tla:9:32-9:32]: Found a polymorphic type: (a79 -> Int) E@18:24:28.111
```

## Input specification

```
---------- MODULE test ----------

EXTENDS Integers, Apalache

\* @type: (Set(a)) => a -> Int;
PolyOper(S) == 
  LET
    \* @type: (a -> Int, a) => a -> Int;
    Add(f,e) == [ x \in DOMAIN f \union {e} |-> 0 ]
  IN FoldSet( Add, [x \in {} |-> 0], S )

Init == TRUE

Next == TRUE

Inv == PolyOper({1}) = [x \in {1} |-> 0]

====================
```

## The command line parameters used to run the tool

`--inv=Inv --length=1`

## Expected behavior

No type error.

## Additional context

This is what the last pass before the 2nd snowcat pass outputs:
```
---------------------------- MODULE 11_OutAnalysis ----------------------------

EXTENDS Integers, Sequences, FiniteSets, TLC, Apalache

(*
  @type: (() => Bool);
*)
Init_si_0000 == TRUE

(*
  @type: (() => Bool);
*)
Next_si_0000 == TRUE

(*
  @type: Bool;
*)
VCInv_si_0 ==
  FoldSet(LET (*
    @type: (((a45 -> Int), a45) => (a45 -> Int));
  *)
  t_2_si_1(f_si_1, e_si_1) == [ x$1 \in DOMAIN f$1 \union {e$1} |-> 0 ]
  IN
  t_2$1, [ x$2 \in {} |-> 0 ], {1})
    = [ x$3 \in {1} |-> 0 ]

(*
  @type: Bool;
*)
VCNotInv_si_0 ==
  ~(FoldSet(LET (*
    @type: (((a45 -> Int), a45) => (a45 -> Int));
  *)
  t_2_si_2(f_si_2, e_si_2) == [ x$4 \in DOMAIN f$2 \union {e$2} |-> 0 ]
  IN
  t_2$2, [ x$5 \in {} |-> 0 ], {1})
    = [ x$6 \in {1} |-> 0 ])

================================================================================

```
Inside `FoldSet`, the LET-defined operator is still marked as having a polymorphic type (`    @type: (((a45 -> Int), a45) => (a45 -> Int));`, however, the unification at the call site should have determined `a45 = Int`.

### PR DESCRIPTION
**Pull request by Kukovec**
- [X] Tests added for any new code
- [X] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [X] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

If #1088 is closed, this fix also closes issue #1085 in the general case.

### CODE REVIEW

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala [hunk 1]
```diff
@@ -0,0 +1,75 @@
...
+import at.forsyte.apalache.tla.lir.TypedPredefs.TypeTagAsTlaType1
+import at.forsyte.apalache.tla.lir.{LetInEx, OperEx, TlaDecl, TlaEx, TlaOperDecl, Typed, TypingException}
+import at.forsyte.apalache.tla.lir.transformations.{TlaExTransformation, TransformationTracker}
+import at.forsyte.apalache.tla.typecheck.etc.{Substitution, TypeUnifier}
+
+/**
+ * LetInTypeSynchronizer re-computes the types of any residual LET-IN defined operators, that were defined
+ * in the scope of a polymorphic operator (e.g. in FoldX). After inlining, any leftover LET-IN operators should have monotypes
+ */
+class LetInTypeSynchronizer(tracker: TransformationTracker) extends TlaExTransformation {
```
Comment (konnov) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:12]: This name is not clear to me. This transformation applies to a very specific pattern that comes from lambdas, or inlining of operators in higher-order operators. Shall we call it `LambdaTypeInliner`? It propagates the type from the body to the let-in definition.

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala [hunk 2]
```diff
@@ -0,0 +1,75 @@
...
+
+      // The solution: Unify the body type and the declaration type, then apply the resulting substitution over the
+      // declaration body
+      val Seq(letInDecl) = defs
+      val bodyType = letInBody.typeTag.asTlaType1()
+      val declType = letInDecl.typeTag.asTlaType1()
+      val unifiedOpt = (new TypeUnifier).unify(Substitution.empty, bodyType, declType)
+
+      unifiedOpt match {
+        case None => throw new TypingException("Could not synchronize type of fold operator.")
```
Comment (konnov) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:34]: In principle, this should never happen, right? It would mean that the specification is ill-typed.

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala [hunk 3]
```diff
@@ -0,0 +1,75 @@
...
+        case Some((subst, unifiedType)) =>
+          val substitutor = new TypeSubstitutor(tracker, subst)
+          val newDecl = letInDecl.copy(body = substitutor(letInDecl.body))(Typed(unifiedType))
+          LetInEx(letInBody, newDecl)(Typed(unifiedType))
+      }
+
+    case letInEx @ LetInEx(letInBody, defs @ _*) =>
+      // assume !isRelevant
```
Comment (konnov) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:42]: what is happening here? Could you add a comment?

**Review by konnov — APPROVED** [review]
That looks good. I only have a few comments about the class name and a missing comment.

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala (hunk 2 above)
Comment (Kukovec) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:34]: Yes, but in the interim, this helps track down cases like #1088

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala (hunk 3 above)
Comment (Kukovec) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:42]: What part of this is unclear/needs comments?

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala (hunk 1 above)
Comment (Kukovec) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:12]: Sure

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala (hunk 3 above)
Comment (konnov) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:42]: This part. What is `!isRelevant`? What happens in the code below?

Comment (Kukovec) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:42]: https://github.com/informalsystems/apalache/blob/e3842c0ce295b87b70e5b3d67874430740aa4eeb/tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala#L15-L22

Comment (konnov) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/LetInTypeSynchronizer.scala:42]: I do not understand, why we should spend 1 hour firing messages, instead of writing two lines of comments?
