### PR TITLE
BUGFIX: `f \in [S -> T]` didn't check `S \subseteq DOMAIN f`

### LINKED ISSUE #1735: Function set membership not properly testing domain
## Description

Apalache does not seem to properly check the function domain when testing membership with a function set.

## Input specification

```
--------------------- MODULE Test ---------------------
EXTENDS Integers
Init == TRUE
Next == TRUE
Inv ==
    LET f == [ x \in {2} |-> 2 ] IN
    LET S == [{ 1, 2 } -> { 2 }] IN
    f \in S
=======================================================
```

## The command line parameters used to run the tool

`apalache-mc check --inv=Inv ~/Test.tla`

## Expected behavior

A model-checking error.
TLC correctly reports the failing invariant.

## System information

- Apalache version [`apalache-mc version`]: `v0.25.1-3-g9f1aecbab`
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: macOS
- JDK version [e.g. OpenJDK 0.8.0]: Temurin-17.0.2+8

### PR DESCRIPTION
**Pull request by Kukovec**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [ ] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

closes #1735

### CODE REVIEW

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala [hunk 1]
```diff
@@ -120,11 +122,25 @@ class SetInRule(rewriter: SymbStateRewriter) extends RewritingRule {
...
+      tla
+        .eql(
+            funsetDom.toNameEx,
+            tla.dom(funCell.toNameEx).as(domType),
+        )
+        .as(BoolT1())
+
+    rewriter.rewriteUntilDone(
+        partialConstraintDomainState.setRex(
+            tla.and(partialConstraintDomainState.ex, domainEx)
```
Comment (thpani) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala:141]: Do we have to call the rewriter twice, or can we just do

```suggestion
    // S = DOMAIN f
    val domainEx =
      tla
        .eql(
            funsetDom.toNameEx,
            tla.dom(funCell.toNameEx).as(domType),
        )
        .as(BoolT1())

    rewriter.rewriteUntilDone(
        nextState.setRex(tla.and(pred.toNameEx, domainEx)
```

**Review by thpani — APPROVED** [review]
Thanks for picking this up!
One question about calling the rewriter twice, othw LGTM 👍

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala (hunk 1 above)
Comment (Kukovec) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/SetInRule.scala:141]: True
