### PR TITLE
Fix unhandled exception on invalid file formats

### LINKED ISSUE #2175: Unhandled expection for unsupported file formats when running `typecheck`
Running on a file with an unsupported extension:

```sh
apalache-mc typecheck src/tla/Option.btla
```

Gives

```
Exception in thread "main" at.forsyte.apalache.infra.PassOptionException: Unsupported file format btla
	at at.forsyte.apalache.infra.passes.options.SourceOption$FileSource$.apply(options.scala:282)
	at at.forsyte.apalache.tla.tooling.opt.TypeCheckCmd.toConfig(TypeCheckCmd.scala:31)
	at at.forsyte.apalache.tla.tooling.opt.ApalacheCommand.read(ApalacheCommand.scala:176)
	at org.backuity.clist.Parser.$anonfun$withCommands$1(Parser.scala:137)
	at org.backuity.clist.Parser.withParsingException(Parser.scala:199)
	at org.backuity.clist.Parser.withCommands(Parser.scala:119)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:90)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:40)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

### PR DESCRIPTION
**Pull request by shonfeder**
Closes #2175

This fixes the processing of CLI configuration params to avoid unhandled
exceptions. The solution is to be honest about the possible failure of
the the `toConfig` method, which maps CLI param inputs to an
instance of `Options.ApalacheConfig`: Since this conversion can fail, 
we let it return a `Try` and this fix ensures that error is handled 
correctly.

Along the way, it removes the atavistic `collectTuningOptions` method,
which shouldn't be needed with the new config management scheme. This
also enables a slight cleanup on the Tracee command.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [x] Documentation added for any new functionality
- [ ] [Entries added to `./unreleased/`][changelog format] for any new functionality

[changelog format]: https://github.com/informalsystems/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change

### CODE REVIEW

File: mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala [hunk 1]
```diff
@@ -70,37 +71,43 @@ class CheckCmd(name: String = "check", description: String = "Check a TLA+ speci
...
-    overrideProperties(tuning, tuningOptions.getOrElse("")) ++ Map("search.outputTraces" -> saveRuns.toString)
+  override def toConfig(): Try[Config.ApalacheConfig] = {
+    val loadedTuningOptions = tuningOptionsFile.map(f => loadProperties(f)).getOrElse(Map())
+    val combinedTuningOptions = overrideProperties(loadedTuningOptions, tuningOptions.getOrElse("")) ++ Map(
+        "search.outputTraces" -> saveRuns.toString)
+
+    super.toConfig().map { cfg =>
+      val newCfg = cfg.copy(
+          checker = cfg.checker.copy(
+              nworkers = nworkers,
```
Comment (konnov) [inline mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala:82]: a question outside of this PR, shall we remove the `nworkers` parameters after all, as we do not have any plans to integrate the multicore branch in the near future?

**Review by konnov — APPROVED** [review]
Looks good to me!

File: mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala (hunk 1 above)
Comment (shonfeder) [reply mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala:82]: Sure! I’ll do as a follow up.

**Comment by shonfeder** [comment]
Thanks for the review.
