### PR TITLE
closes #193

### LINKED ISSUE #193: [BUG] Running check on a module without an Init operator raises an unhandeled exception
Running `check` on a `tla` file that doesn't define an `Init` operator results in an unhandeled exception:

**To Reproduce**

Create an empty module:

In `M.tla`:

```tla
---- MODULE M -----------------------------------------------------
================================================================================
```

Check it with apalache

```sh
$ apalache-mc check M.tla
```

**Expected behavior**

A user-friendly error message describing what's missing, with reference to documentation.

**Log files**

```
Checker options: filename=test/tla/tla-path-tests/ImportingModule.tla, init=, next=, inv= I@18:35:40.984
PASS #0: SanyParser                                               I@18:35:41.457
Parsing file /home/sf/Sync/informal-systems/apalache/apalache-core/test/tla/tla-path-tests/ImportingModule.tla
Parsing file /home/sf/Sync/informal-systems/apalache/apalache-core/test/tla/tla-path-tests/ImportedModule.tla
PASS #1: ConfigurationPass                                        I@18:35:41.746
  > Loading TLC configuration from ImportingModule.cfg            I@18:35:41.748
  > No TLC configuration found; skipping                          I@18:35:41.756
PASS #2: UnrollPass                                               I@18:35:41.769
  > Unroller                                                      I@18:35:41.774
PASS #3: InlinePass                                               I@18:35:41.791
  > InlinerOfUserOper                                             I@18:35:41.794
  > LetInExpander                                                 I@18:35:41.795
PASS #4: PrimingPass                                              I@18:35:41.798
  > Introducing InitPrimed for Init'                              I@18:35:41.803
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.util.NoSuchElementException: key not found: Init)
Unhandled exception                                               E@18:35:41.811
java.util.NoSuchElementException: key not found: Init
	at scala.collection.MapLike.default(MapLike.scala:232)
	at scala.collection.MapLike.default$(MapLike.scala:231)
	at scala.collection.AbstractMap.default(Map.scala:59)
	at scala.collection.MapLike.apply(MapLike.scala:141)
	at scala.collection.MapLike.apply$(MapLike.scala:140)
	at scala.collection.AbstractMap.apply(Map.scala:59)
	at at.forsyte.apalache.tla.assignments.passes.PrimingPassImpl.execute(PrimingPassImpl.scala:63)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:147)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:196)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:81)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:42)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

**Desktop (please complete the following information):**
 - OS: Arch
 - JDK version "1.8.0_252"
 - Version 0.7.0

This should be a relatively easy beginner issue for the code bas, so I'll take this if no one objects.

### PR DESCRIPTION
**Pull request by konnov**
This PR fixes bug #193:

- [x] `ConfigurationPassImpl` checks for the presence of the operators that propagate via parameters or TLC config: the initialization predicate, the transition predicate, etc.
- [x] `ConfigurationPassImpl` sets the default values for `--init` and `--next`, if they are not set by the user.

### CODE REVIEW

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala [hunk 1]
```diff
@@ -3,27 +3,29 @@ package at.forsyte.apalache.tla.pp.passes
...
 import com.google.inject.Inject
 import com.google.inject.name.Named
 import com.typesafe.scalalogging.LazyLogging
 import org.apache.commons.io.FilenameUtils
 
 /**
   * The pass that collects the configuration parameters and overrides constants and definitions.
+  * This pass also overrides attributes in the PassOptions object:
+  * checker.init, checker.next, checker.cinit, checker.inv. In general, passes should not override options.
+  * This is a reasonable exception to this rule.
```
Comment (shonfeder) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:23]: A word here about why this exception is reasonable would be useful.

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala [hunk 2]
```diff
@@ -43,40 +45,72 @@ class ConfigurationPassImpl @Inject()(val options: PassOptions,
...
   override def execute(): Boolean = {
-    var module = tlaModule.get
+    // try to read from the TLC configuration file
+    val configuredModule = tryConfigureFromTlcConfig(tlaModule.get)
 
+    // dump the configuration result
+    val outdir = options.getOrError("io", "outdir").asInstanceOf[Path]
+    PrettyWriter.write(configuredModule, new File(outdir.toFile, "out-config.tla"))
+
+    // set fallback options
```
Comment (shonfeder) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:55]: Suggested since it literally just repeats the name of the function, adding noise but no signal

```suggestion
```

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala [hunk 3]
```diff
@@ -43,40 +45,72 @@ class ConfigurationPassImpl @Inject()(val options: PassOptions,
...
+    setFallbackOptions()
+
+    // make sure that the operators are defined
```
Comment (shonfeder) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:58]:
```suggestion
    // make sure that the required operators are defined
```

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala [hunk 4]
```diff
@@ -43,40 +45,72 @@ class ConfigurationPassImpl @Inject()(val options: PassOptions,
...
+    ensureDeclarationsArePresent(configuredModule)
+
+    outputTlaModule = Some(configuredModule)
+    true
+  }
+
+  // if checker.init and checker.next are not set, set them to Init and Next, respectively
+  private def setFallbackOptions(): Unit = {
+    if (options.get("checker", "init").isEmpty) {
+      logger.info("  > Option --init is not set. Using Init")
```
Comment (shonfeder) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:68]: This seems to me like natural and expected behavior, and not very informative. I worry that this adds noise without much benefit. So I'd suggest instead including information about this defaulting behavior into the CLI help, and demoting this logging to

```suggestion
      logger.debug("  > Option --init is not set. Using Init")
```

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala [hunk 5]
```diff
@@ -43,40 +45,72 @@ class ConfigurationPassImpl @Inject()(val options: PassOptions,
...
+      options.set("checker.init", "Init")
+    }
+    if (options.get("checker", "next").isEmpty) {
+      logger.info("  > Option --next is not set. Using Next")
```
Comment (shonfeder) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:72]: Suggested for the same reason as above:

```suggestion
      logger.debug("  > Option --next is not set. Using Next")
```

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala [hunk 6]
```diff
@@ -43,40 +45,72 @@ class ConfigurationPassImpl @Inject()(val options: PassOptions,
...
+
+    // make sure that the operators are defined
+    ensureDeclarationsArePresent(configuredModule)
+
+    outputTlaModule = Some(configuredModule)
+    true
+  }
+
+  // if checker.init and checker.next are not set, set them to Init and Next, respectively
+  private def setFallbackOptions(): Unit = {
```
Comment (shonfeder) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:66]: Wouldn't it better to just set the `default` values of the CLI?

https://github.com/informalsystems/apalache/blob/4d6912e9a57a02bc28422fdd28924fa07788abb4/mod-tool/src/main/scala/at/forsyte/apalache/tla/tooling/opt/CheckCmd.scala#L27-L30

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala [hunk 7]
```diff
@@ -96,14 +130,46 @@ class ConfigurationPassImpl @Inject()(val options: PassOptions,
...
+    // rewrite constants and declarations
+    new ConstAndDefRewriter(tracker)(configuredModule)
+  }
 
-    // dump the result of preprocessing
-    val outdir = options.getOrError("io", "outdir").asInstanceOf[Path]
-    PrettyWriter.write(rewritten, new File(outdir.toFile, "out-config.tla"))
+  // Make sure that all operators passed via --init, --cinit, --next, --inv are present.
+  private def ensureDeclarationsArePresent(mod: TlaModule): Unit = {
+    def assertDecl(role: String, name: String): Unit = {
```
Comment (shonfeder) [inline tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:139]: We might dry this out a bit, and, imo, make the intention clearer to readers, by moving the "optionality" logic into this helper. E.g., make `assertDecl` something like

```suggestion
    def assertDecl(role: String, name: Option[String], optiona: Bool): Unit = {
```

And then move all the checking logic here, then making the checks just look like

```scala
assertDecl("the initialization predicate", options.get[String]("checker", "init"), optional = False)
assertDecl("the constant initialization predicate", options.get[String]("checker", "cinit"), optional = True)
...
```

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala [hunk 8]
```diff
@@ -27,8 +27,8 @@ class CheckerExceptionAdapter @Inject()(sourceStore: SourceStore,
     case err: SanyException =>
       NormalErrorMessage("Error by TLA+ parser: " + err.getMessage)
 
-    case err: TLCConfigurationError =>
-      NormalErrorMessage(err.getMessage)
+    case err: ConfigurationError =>
+      NormalErrorMessage("Configuration error (see the manual): " + err.getMessage)
```
Comment (shonfeder) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala:31]: Perhaps we can add the link to the relevant section of the manual here?

**Comment by shonfeder** [comment]
Oh, and do we record bug fixes in the change log?

**Comment by konnov** [comment]
yes, we do, but I forget to do that every now and then

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala (hunk 4 above)
Comment (shonfeder) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:68]: I was under the impression that the documented and expected behavior is to use the `Init` operator unless overriden by explicitly supplying an argument via `--init`. Is this correct, then I don't see how printing out that the expected behavior is happening can help users who encounter unexpected behavior :) But if my assumption is wrong, and this behavior is not documented and expected, then I'd be in favor of changing the behavior or adjusting the expectations instead of adding to the (already quite verbose) output?

perhaps there are some dimensions of the info logged here that I'm not appreciating tho.

In any case, I wouldn't block on this :)

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala (hunk 7 above)
Comment (shonfeder) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:139]: I see what you mean about the invariants case, that might undercut any gains in readability. I agree its clear enough.

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala (hunk 4 above)
Comment (andrey-kuprianov) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:68]: it's just that not everyone might read the docs before trying the tool... at least I do this quite often;) In general, I don't have any strong opinion here; whatever @Igor decides is fine with me. 

What would be nice is at some point to discuss between all of us the general guidelines on what we log, how much, and in what way.

**Comment by konnov** [comment]
@shonfeder, good point. We were supplying default values for `--init` and `--next` until recently. However, once Andrey introduced the parser for TLC configuration files, we could not do that anymore. Essentially, to parse a TLC configuration file one needs a parsed TLA spec. Only after figuring out what is in the configuration file, we can set the fallback options, if needed.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala (hunk 8 above)
Comment (konnov) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala:31]: Yeah, I was thinking about providing the link. The only problem is that the link is quite long.

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala (hunk 4 above)
Comment (konnov) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:67]: Let's make it `debug` for now. The output is sometimes too detailed.

File: tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala (hunk 6 above)
Comment (konnov) [reply tla-pp/src/main/scala/at/forsyte/apalache/tla/pp/passes/ConfigurationPassImpl.scala:65]: True, but this does not work for the reasons in my earlier comment.

**Comment by konnov** [comment]
Just merged it, so it is not blocking the release of 0.7.1

**Comment by shonfeder** [comment]
Thanks for explaining!
