### PR TITLE
Shai: Return parsing pass error data in RPCs

### LINKED ISSUE #2199: Shai: Return proper data from parse errors
Some followup is needed to #2186, I missed picking up the parser errors, since those are all currently handled by exceptions. I should be able to pick them up by wrapping the outerlayer in the Sany pass with a `Try`

### PR DESCRIPTION
**Pull request by shonfeder**
Closes #2199, #2204

(See #2234 for additional notes on context and the motivation for this approach).

- Catches `SanyException`s from the highest level of the SANY parser
pass and makes these available in the `PassResult`.
- Promotes the general RPC error data into protbuf specs, allowing more
consistentcy and reducing the amount of dynamic JSON.
- Includes some light refactoring as incidental cleanup.
- Updates tests.

-------

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)

### CODE REVIEW

File: passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala [hunk 1]
```diff
@@ -89,25 +95,29 @@ class SanyParserPassImpl @Inject() (
...
-      sortedModule <- sortDeclarations(rootModule)
-      _ <- saveLoadedModule(sortedModule)
-    } yield sortedModule
+    try {
+      parseSource(options.input.source)
+    } catch {
+      case err: SanyException =>
+        val msg = err.getMessage()
+        logger.error(s"Parsing error: ${msg}")
+        passFailure(List(msg), ExitCodes.ERROR)
```
Comment (thpani) [inline passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala:109]: It think this obsoletes one path in some of the exception adapters, e.g.

https://github.com/informalsystems/apalache/blob/7477b1be3dae41b187298427d2559da3d4bf1f0d/tla-io/src/main/scala/at/forsyte/apalache/tla/imp/ParserExceptionAdapter.scala#L18-L19

File: passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala [hunk 2]
```diff
@@ -89,25 +95,29 @@ class SanyParserPassImpl @Inject() (
...
-            case FileSource(file, _)           => loadFromTlaFile(file)
-          }
-      }
-      sortedModule <- sortDeclarations(rootModule)
-      _ <- saveLoadedModule(sortedModule)
-    } yield sortedModule
+    try {
+      parseSource(options.input.source)
+    } catch {
+      case err: SanyException =>
```
Comment (thpani) [inline passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala:106]: Could you explain why we catch `SanyException` here, but not `AnnotationParserError` (like in `ParserExceptionAdapter`)?

File: passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala [hunk 3]
```diff
@@ -89,25 +95,29 @@ class SanyParserPassImpl @Inject() (
...
+        val msg = err.getMessage()
+        logger.error(s"Parsing error: ${msg}")
```
Comment (thpani) [inline passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala:108]: I think this closes #2204

**Review by thpani — APPROVED** [review]
Looks good, also nice work on replacing string/JSON with more structured protobuf data!

Just a question and a comment on how this relates to our current exception adapters.

**Comment by shonfeder** [comment]
Very good question about the relation to the exception adapters. I'll need to do a grep of the codebase to ensure that:

- All places where `SanyException` are raised are now caught by this `Either`
- That there are not additional exceptions we use to signal parse errors, which should also be caught.

Once those are addressed, I should remove those cases from the exception adapters.

File: passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala (hunk 2 above)
Comment (shonfeder) [reply passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala:106]: I just didn't realize that this would be needed, and no tests or static analysis was able to warn me. Thank you for catching this!

Comment (thpani) [reply passes/src/main/scala/at/forsyte/apalache/tla/passes/imp/SanyParserPassImpl.scala:106]: 😬
