### PR TITLE
Manual assignments

### LINKED ISSUE #181: [FEATURE] Assignment annotations
Sometimes the assignment finder fails to find assignments because it is buggy: #157

Apart from fixing the bug in #157, we should introduce assignment annotations and let the assignment solver consume them. This will give the users a way to work around bugs. Moreover, some users may find it more convenient to label some expressions as assignments.

### PR DESCRIPTION
**Pull request by Kukovec**
Closes #181 .

### CODE REVIEW

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/ManualAssignments.scala [hunk 1]
```diff
@@ -0,0 +1,38 @@
...
+  * manually annotate where they expect assignments in their specifications (with BmcOper.assign)
+  *
+  * This changes automatic assignment detection in the following way:
+  * If, for a given (primed) variable `v`, there exists at least one manual assignment
+  * [ v' := ... ], then all expressions of the form [ v' = ... ] are ignored as assignment candidates
+  * Manual assignments are still required to satisfy both the acyclicity and the covering properties,
+  * or assignment finding will fail.
+  *
+  * Any variable, for which no manual assignemt exists, is handled in the standard way.
+  */
```
Comment (konnov) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/ManualAssignments.scala:17]:
```suggestion
*
* @author Jure Kukovec
*/ 
```

**Review by konnov — APPROVED** [review]
Looks great! In general, we have to think about reducing the code complexity (or maybe adding more comments) in the assignment finder. The code still looks too complex to me.
