### PR TITLE
closes #762: create $HOME/.tlaplus if it does not exist

### LINKED ISSUE #762: [BUG] Unable to enable statistics
## Description

I have statistics reporting enabled in the toolbox and would like to enable statistics for Apalache, but I keep getting an exception in thread "main" java.io.IOException: No such file or directory.

## Input specification

N/A

## The command line parameters used to run the tool

`apalache config --enable-stats=true`

## Expected behavior

Statistics are enabled.

## Log files

```
$ apalache config --enable-stats=true
Assuming you bind-mounted your local directory into /var/apalache...
# Tool home: /opt/apalache
# Package:   /opt/apalache/mod-distribution/target/apalache-pkg-0.15.4-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/opt/apalache/src/tla
#
Picked up _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true
# APALACHE version 0.15.4-SNAPSHOT build v0.15.3-15-g8c71e2c
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Configuring Apalache                                              I@00:52:52.995
Statistics collection is ON.                                      I@00:52:52.997
This also enabled TLC and TLA+ Toolbox statistics.                I@00:52:52.997
It took me 0 days  0 hours  0 min  0 sec                          I@00:52:53.000
Total time: 0.3 sec                                               I@00:52:53.001
Exception in thread "main" java.io.IOException: No such file or directory
        at java.base/java.io.UnixFileSystem.createFileExclusively(Native Method)
        at java.base/java.io.File.createNewFile(File.java:1024)
        at util.ExecutionStatisticsCollector.set(ExecutionStatisticsCollector.java:164)
        at at.forsyte.apalache.tla.Tool$.configure(Tool.scala:361)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:113)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
```

```
$ apalache version
Assuming you bind-mounted your local directory into /var/apalache...
# Tool home: /opt/apalache
# Package:   /opt/apalache/mod-distribution/target/apalache-pkg-0.15.4-SNAPSHOT-full.jar
# JVM args: -Xmx4096m -DTLA-Library=/opt/apalache/src/tla
#
Picked up _JAVA_OPTIONS: -Djdk.net.URLClassPath.disableClassPathURLCheck=true
# APALACHE version 0.15.4-SNAPSHOT build v0.15.3-15-g8c71e2c
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

0.15.4-SNAPSHOT build v0.15.3-15-g8c71e2c
EXITCODE: OK
```

## System information

- Apalache version [`apalache-mc version`]: 0.15.4-SNAPSHOT build v0.15.3-15-g8c71e2c
- OS [e.g. Ubuntu Linux or Mac OS, and the current version]: Debian 10
- JDK version [e.g. OpenJDK 0.8.0]:
```
openjdk version "11.0.9.1" 2020-11-04
OpenJDK Runtime Environment (build 11.0.9.1+1-post-Debian-1deb10u2)
OpenJDK 64-Bit Server VM (build 11.0.9.1+1-post-Debian-1deb10u2, mixed mode, sharing)
```

### PR DESCRIPTION
**Pull request by konnov**
This PR fixes bug #762. It creates the directory `$HOME/.tlaplus` if such a directory does not exist. Also, this PR adds exception processing around the statistics collector.

PS: I will create a PR in tlaplus to create the directory in tla2tools too, as it is an obvious issue.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

### CODE REVIEW

File: mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala [hunk 1]
```diff
@@ -354,22 +354,48 @@ object Tool extends App with LazyLogging {
...
+    if (configDir.exists()) {
+      true
+    } else {
+      try {
+        configDir.mkdir()
+        true
+      } catch {
+        case e: Exception =>
+          logger.warn(e.getMessage)
+          logger.warn(s"Unable to create the directory $configDir. The statistics will not be collected.")
```
Comment (shonfeder) [inline mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala:393]: This function is general more general than stat collection. It could end up getting called for other configuration setting/editing, so I think probably better not to put the stats remark in here. Instead, how about we handle that in the else branch of the `submitStats` handler:

```suggestion
          logger.warn(s"Unable to create the directory $configDir.")
```

File: mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala [hunk 2]
```diff
@@ -354,22 +354,48 @@ object Tool extends App with LazyLogging {
...
+              statCollector.set(Selection.NO_ESC)
+              logger.info("Statistics collection is OFF.")
+              logger.info("This also disabled TLC and TLA+ Toolbox statistics.")
+            }
+          } catch {
+            case e: Exception =>
+              logger.warn(e.getMessage)
+              logger.warn(s"Unable to update statistics configuration. The other features will keep working.")
+          }
         }
```
Comment (shonfeder) [inline mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala:375]: I suggest adding an else branch here to report to the user when the stats cannot be enabled (as a result of the dir creationg/check failing).

File: test/tla/cli-integration-tests.md [hunk 3]
```diff
@@ -1293,3 +1293,25 @@ Typing input error: Expected a type annotation for VARIABLE x
 EXITCODE: ERROR (99)
 ```
 
+## Running the config command
```
Comment (shonfeder) [inline test/tla/cli-integration-tests.md:1296]: Should we should check the case when the directory needs to be created, and when it cannot be created? We should be able to do this relatively easily in the CI by overriding `user.home` I think? For the case when the dir cannot be created, perhaps we could just configure it be created at a non-existent path?

Comment (konnov) [reply test/tla/cli-integration-tests.md:1296]: I guess, this is happening already, as the default image does not have the directory `$HOME/.tlaplus`. We just did not have a test for `config`, and this happened to produce a bug :)

File: mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala (hunk 2 above)
Comment (konnov) [reply mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala:379]: Just did that.

**Review by shonfeder — APPROVED** [review]
