### PR TITLE
Strip long ZIO traces on startup error

### LINKED ISSUE #2676: Catch IOException when Apalache server binds in-use address
Binding an in-use address (viz. port) from Shai / Apalache server results in a lengthy error trace.

We should catch and handle the exception.

<details>
 <summary>Example stacktrace</summary>

```
~/s/a/unstable ❯❯❯ apalache-mc server --write-intermediate=true
10:38:56.015 [main] INFO at.forsyte.apalache.tla.tooling.opt.ServerCmd -- Loading configuration
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Output directory: /Users/thomas/src/apalache/unstable/_apalache-out/server/2023-07-28T10-38-56_9205152170509149665
# APALACHE version: v0.41.2-4-g561d08f38 | build: v0.41.2-4-g561d08f38 I@10:38:56.201
Starting server on port 8822...                                   I@10:38:56.207
The Apalache server is running on port 8822. Press Ctrl-C to stop.
Fiber failed.
A checked error was not handled.
java.io.IOException: Failed to bind to address 0.0.0.0/0.0.0.0:8822
	at io.grpc.netty.NettyServer.start(NettyServer.java:328)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:185)
	at io.grpc.internal.ServerImpl.start(ServerImpl.java:94)
	at scalapb.zio_grpc.Server$ServiceImpl.$anonfun$start$1(Server.scala:44)
	at zio.internal.FiberContext.evaluateNow(FiberContext.scala:365)
	at zio.internal.FiberContext.$anonfun$fork$15(FiberContext.scala:779)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.net.BindException: Address already in use
	at java.base/sun.nio.ch.Net.bind0(Native Method)
	at java.base/sun.nio.ch.Net.bind(Net.java:555)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.netBind(ServerSocketChannelImpl.java:337)
	at java.base/sun.nio.ch.ServerSocketChannelImpl.bind(ServerSocketChannelImpl.java:294)
	at io.netty.channel.socket.nio.NioServerSocketChannel.doBind(NioServerSocketChannel.java:141)
	at io.netty.channel.AbstractChannel$AbstractUnsafe.bind(AbstractChannel.java:562)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.bind(DefaultChannelPipeline.java:1334)
	at io.netty.channel.AbstractChannelHandlerContext.invokeBind(AbstractChannelHandlerContext.java:600)
	at io.netty.channel.AbstractChannelHandlerContext.bind(AbstractChannelHandlerContext.java:579)
	at io.netty.channel.DefaultChannelPipeline.bind(DefaultChannelPipeline.java:973)
	at io.netty.channel.AbstractChannel.bind(AbstractChannel.java:260)
	at io.netty.bootstrap.AbstractBootstrap$2.run(AbstractBootstrap.java:356)
	at io.netty.util.concurrent.AbstractEventExecutor.runTask(AbstractEventExecutor.java:174)
	at io.netty.util.concurrent.AbstractEventExecutor.safeExecute(AbstractEventExecutor.java:167)
	at io.netty.util.concurrent.SingleThreadEventExecutor.runAllTasks(SingleThreadEventExecutor.java:470)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:569)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:997)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	... 1 more

Fiber:Id(1690533536298,1) was supposed to continue to:
  a future continuation at zio.ZIO.unit(ZIO.scala:2151)
  a future continuation at <unknown>.<unknown>(Server.scala:0)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:291)
  a future continuation at zio.ZManaged$.makeExit(ZManaged.scala:2083)
  a future continuation at zio.ZManaged.map(ZManaged.scala:484)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:337)
  a future continuation at zio.ZManaged.map(ZManaged.scala:484)
  a future continuation at zio.ZManaged.map(ZManaged.scala:484)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:337)
  a future continuation at zio.ZManaged.flatMap(ZManaged.scala:337)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZIO.bracket_(ZIO.scala:291)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1089)
  a future continuation at zio.ZIO.run(ZIO.scala:1764)
  a future continuation at zio.ZManaged.use(ZManaged.scala:1088)
  a future continuation at zio.ZIO.exitCode(ZIO.scala:626)

Fiber:Id(1690533536298,1) execution trace:
  at scalapb.zio_grpc.Server$ServiceImpl.start(Server.scala:44)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZManaged$.makeExit(ZManaged.scala:2082)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4470)
  at zio.ZManaged.flatMap(ZManaged.scala:336)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.ZManaged.flatMap(ZManaged.scala:337)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at at.forsyte.apalache.shai.v1.cmdExecutor.ZioCmdExecutor$ZCmdExecutor$$anon$3.bind(ZioCmdExecutor.scala:27)
  at zio.ZIO$.runtime(ZIO.scala:4000)
  at zio.ZIO$.executor(ZIO.scala:2879)
  at zio.ZIO$.runtime(ZIO.scala:3999)
  at zio.ZIO$.runtime(ZIO.scala:3998)
  at zio.ZIO$.runtime(ZIO.scala:3998)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4470)
  at scalapb.zio_grpc.ZBindableService$$anon$1.bindService(ZBindableService.scala:31)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at zio.ZManaged$.fromEffect(ZManaged.scala:1883)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at at.forsyte.apalache.shai.v1.RpcServer.createCmdExecutorService(RpcServer.scala:28)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZManaged.flatMap(ZManaged.scala:336)
  at zio.ZManaged.flatMap(ZManaged.scala:337)
  at zio.ZManaged.map(ZManaged.scala:484)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at at.forsyte.apalache.shai.v1.transExplorer.ZioTransExplorer$ZTransExplorer$$anon$3.bind(ZioTransExplorer.scala:29)
  at zio.ZIO$.runtime(ZIO.scala:4000)
  at zio.ZIO$.executor(ZIO.scala:2879)
  at zio.ZIO$.runtime(ZIO.scala:3999)
  at zio.ZIO$.runtime(ZIO.scala:3998)
  at zio.ZIO$.runtime(ZIO.scala:3998)
  at zio.ZIO$AccessPartiallyApplied$.apply(ZIO.scala:4470)
  at scalapb.zio_grpc.ZBindableService$$anon$1.bindService(ZBindableService.scala:31)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZManaged.mapM(ZManaged.scala:517)
  at zio.ZManaged$.fromEffect(ZManaged.scala:1883)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:563)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.ZIO.run(ZIO.scala:1764)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at at.forsyte.apalache.shai.v1.RpcServer.createTransExplorerService(RpcServer.scala:26)
  at zio.ZRef$.make(ZRef.scala:756)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO.bracket_(ZIO.scala:291)
  at zio.internal.FiberContext.evaluateNow(FiberContext.scala:559)
  at zio.ZIO.provideSome(ZIO.scala:1266)
  at zio.ZManaged.flatMap(ZManaged.scala:336)
  at zio.ZManaged$.succeed(ZManaged.scala:2497)
  at zio.ZManaged.flatMap(ZManaged.scala:336)
  at zio.ZManaged$.succeed(ZManaged.scala:2497)
  at zio.ZManaged.flatMap(ZManaged.scala:336)
  at zio.ZManaged$.fromEffect(ZManaged.scala:1883)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:160)
  at zio.internal.FiberContext$InterruptExit$.apply(FiberContext.scala:153)
  at zio.ZIO$.effectSuspendTotal(ZIO.scala:2837)
  at zio.ZIO$.bracketExit(ZIO.scala:2437)

Fiber:Id(1690533536298,1) was spawned by:

Fiber:Id(1690533536237,0) was supposed to continue to:
  a future continuation at zio.App.main(App.scala:60)
  a future continuation at zio.App.main(App.scala:59)

Fiber:Id(1690533536237,0) ZIO Execution trace: <empty trace>

Fiber:Id(1690533536237,0) was spawned by: <empty trace>
```

</details>

### PR DESCRIPTION
**Pull request by fan-tom**
Closes #2676

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [ ] [Entries added to `./unreleased/`][changelog format] for any new functionality

[changelog format]: https://github.com/informalsystems/apalache/blob/main/CONTRIBUTING.md#how-to-record-a-change

### CODE REVIEW

**Comment by shonfeder** [comment]
Dope! Thanks for this fix too :raised_hands: 

Shall I add a test onto this branch? Os is there something else you wanted to do here before marking it as ready for review?

File: shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala [hunk 1]
```diff
@@ -39,6 +39,13 @@ class RpcServer(override val port: Int) extends ServerMain with LazyLogging {
   // https://github.com/informalsystems/apalache/issues/2622
   override def builder: (x0) forSome { type x0 <: ServerBuilder[x0] } =
     super.builder.maxInboundMessageSize(8 * 1024 * 1024)
+
+  override def run(args: List[String]) = {
+    myAppLogic.catchAll { t =>
+      logger.error("Error while starting Apalache server", t)
```
Comment (shonfeder) [inline shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala:45]: Could we check the error, and if it is a socket binding problem, just report that without logging the traceback? Otherwise, reporting the full traceback would be helpful, since the failure is for an unknown reason.

**Comment by fan-tom** [comment]
> Shall I add a test onto this branch? Os is there something else you wanted to do here before marking it as ready for review?

I will finish the PR, just wanted to first understand whether it is a right direction

File: shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala (hunk 1 above)
Comment (fan-tom) [reply shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala:45]: Will try

**Comment by shonfeder** [comment]
Awesome. Drafts to share and test out ideas are most welcome. This is definitely in the right direction.

File: shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala [hunk 2]
```diff
@@ -39,10 +42,24 @@ class RpcServer(override val port: Int) extends ServerMain with LazyLogging {
   // https://github.com/informalsystems/apalache/issues/2622
   override def builder: (x0) forSome { type x0 <: ServerBuilder[x0] } =
     super.builder.maxInboundMessageSize(8 * 1024 * 1024)
+
+  override def run(args: List[String]) = {
+    myAppLogic.catchAll { t =>
+      t match {
+        // treat "post already in use" error specially
+        case e: IOException if e.getCause.isInstanceOf[BindException] =>
+          logger.error(s"${RpcServer.STARTUP_ERROR_PROMPT} ${e.getMessage}: ${e.getCause.getMessage}")
```
Comment (fan-tom) [inline shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala:51]: Should I print using `console` instead?

File: test/tla/cli-integration-tests.md [hunk 3]
```diff
@@ -3978,6 +3978,31 @@ The Apalache server is running on port 8888. Press Ctrl-C to stop.
...
+
+Try to start the Apalache server on the occupied port,
+redirect its output to the file,
+save its exit code,
+strip logger prompt 
+and exit with status code of the server
+```sh
+$ apalache-mc server --port=8888 1>out 2>out; ext=$? && cat out | sed -E 's/E@.*$//' && exit $ext
+...
+Error while starting Apalache server: Failed to bind to address 0.0.0.0/0.0.0.0:8888: Address already in use
```
Comment (fan-tom) [inline test/tla/cli-integration-tests.md:3996]: Actually, this string has a suffix, added by logger, that contains a time, that's why I need all this crazy stuff when running the server, to cut it off

File: shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala (hunk 2 above)
Comment (shonfeder) [reply shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala:51]: A logged error is perfect here.

File: shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala [hunk 4]
```diff
@@ -39,10 +42,24 @@ class RpcServer(override val port: Int) extends ServerMain with LazyLogging {
   // https://github.com/informalsystems/apalache/issues/2622
   override def builder: (x0) forSome { type x0 <: ServerBuilder[x0] } =
     super.builder.maxInboundMessageSize(8 * 1024 * 1024)
+
+  override def run(args: List[String]) = {
+    myAppLogic.catchAll { t =>
+      t match {
+        // treat "post already in use" error specially
```
Comment (shonfeder) [inline shai/src/main/scala/at/forsyte/apalache/shai/v1/RpcServer.scala:49]:
```suggestion
        // treat "port already in use" error specially
```

File: test/tla/cli-integration-tests.md (hunk 3 above)
Comment (shonfeder) [reply test/tla/cli-integration-tests.md:3996]: Its a beautifully written black box test, given the constraints of our wonky system. Kudos to working out all it fits together!

**Review by shonfeder — APPROVED** [review]
Beautiful and perfectly targeted fix! I'll add the changelog entry. 

Thanks for another great contribution :)

**Comment by shonfeder** [comment]
It looks like a race condition (or something) may be causing our integration tests to hang on this test. E.g.: https://github.com/informalsystems/apalache/actions/runs/7663132920/job/20885458232?pr=2811#step:7:499

**Comment by fan-tom** [comment]
Regarding docker test seems I understand why so: because socat is run on host, while apalache-mc inside the docker, they don't conflict on port.
Regarding integration-tests, IDK the reson, maybe socat is absent, so again, no port conflicts.
And while the latter may be resolved, IDK how to approach the docker case, since tests are ran outside the docker, so if we occupy port before we start the container, the error will be from the docker, not from the apalache

**Comment by shonfeder** [comment]
Thanks for the debugging and diagnosis. I understand the problems now, and is seems clearly to be a limitation of our CI plumbing. I should have time to figure out a fir this week, and I'll aim to have this merged in before the weekend.

**Comment by shonfeder** [comment]
My proposed "fix" here is just to not run the tests :sweat_smile: -- accounting for the docker case is just too tricky to be worth the effort for this particular behavior.

Thanks again for the fix here!
