### PR TITLE
Fix the use of oracles in the arrays encoding

### LINKED ISSUE #1152: [BUG] Sets becoming unconstrained after set minus operation
## Description

In the arrays encoding, when set minus is used it leaves the updated set unconstrained. This is due to a break in the chain of SSA constraints.

## Input specification

This bug was found when testing the encoding with [SetSndRcv.tla](https://github.com/informalsystems/apalache-tests/blob/master/performance/array-encoding/SetSndRcv.tla).

## The command line parameters used to run the tool

`check --inv=Inv --smt-encoding=arrays --length=4 --cinit=CInit4 SetSndRcv.tla`

## Expected behavior

No invariant violation.

## Additional context

Counter-example generated:

```
---------------------------- MODULE counterexample ----------------------------

EXTENDS SetSndRcv

(* Constant initialization state *)
ConstInit == Values = { 0, 1, 2, 3, 4 }

(* Initial state *)
State0 ==
  Values = { 0, 1, 2, 3, 4 }
    /\ medium = {}
    /\ receiver = {}
    /\ sender = { 0, 1, 2, 3, 4 }

(* Transition 0 to State1 *)
State1 ==
  Values = { 0, 1, 2, 3, 4 }
    /\ medium = {0}
    /\ receiver = {}
    /\ sender = { 1, 2, 3, 4 }

(* Transition 1 to State2 *)
State2 ==
  Values = { 0, 1, 2, 3, 4 }
    /\ medium = {0}
    /\ receiver = {}
    /\ sender = {}

(* Transition 1 to State3 *)
State3 == Values = { 0, 1, 2, 3, 4 }/\ medium = {}/\ receiver = {}/\ sender = {}

(* The following formula holds true in the last state and violates the invariant *)
InvariantViolation == sender = {} /\ medium = {} /\ receiver = {}

================================================================================
```

### PR DESCRIPTION
**Pull request by rodrigo7491**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

Oracles currently produce conjunctions of implications. In the arrays encoding, if the lhs of an implication does not hold and its rhs contains an array update we need to explicitly state that the array stays unchanged. This is done implicitly in the current encoding. Closes #1152.

### CODE REVIEW

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala [hunk 1]
```diff
@@ -441,22 +448,30 @@ class CherryPick(rewriter: SymbStateRewriter) {
...
         }
       }
 
-      val assertions = toPickFrom.zip(memberSets).zipWithIndex map (nthIn _).tupled
+      val assertions = (toPickFrom.zip(memberSets).zipWithIndex map (nthIn _).tupled).unzip
       // add the cell to the arena
       nextState = nextState.updateArena(_.appendHas(resultCell, picked))
       // (chosen = 1 /\ in(z_i, R) = in(c_i, S_1)) \/ (chosen = 2 /\ in(z_i, R) = in(d_i, S_2))
-      solverAssert(oracle.caseAssertions(nextState, assertions :+ elseAssert))
+      solverAssert(oracle.caseAssertions(nextState, assertions._1 :+ elseAssert, assertions._2 :+ ValEx(TlaBool(true))))
```
Comment (konnov) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala:474]: Extract `assertions._1` and `assertions._2` to `membershipAssertions` and `nonMembershipAssertions`? Just for documentation purposes.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala [hunk 2]
```diff
@@ -33,21 +34,25 @@ class IntOracle(val intCell: ArenaCell, nvalues: Int) extends Oracle {
...
-   * @param assertions a sequence of assertions, one per oracle value
+   * @param state          a symbolic state
+   * @param assertions     a sequence of assertions, one per oracle value
+   * @param elseAssertions an optional sequence of assertions, one per oracle value
    * @return an expression ite(oracle = 0, ite(oracle = 1, ...))
    */
-  override def caseAssertions(state: SymbState, assertions: Seq[TlaEx]): TlaEx = {
+  override def caseAssertions(state: SymbState, assertions: Seq[TlaEx], elseAssertions: Seq[TlaEx] = Seq()): TlaEx = {
+    if (elseAssertions.nonEmpty & assertions.size != elseAssertions.size) {
+      throw new IllegalStateException(s"Invailid call to Oracle, malformed elseAssertions")
```
Comment (konnov) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala:44]:
```suggestion
      throw new IllegalStateException(s"Invalid call to Oracle, malformed elseAssertions")
```

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala [hunk 3]
```diff
@@ -33,21 +34,25 @@ class IntOracle(val intCell: ArenaCell, nvalues: Int) extends Oracle {
...
       case 0 => state.arena.cellTrue().toNameEx
 
       case 1 => assertions.head
 
       case _ =>
-        val es = assertions
-          .slice(0, nvalues)
-          .zipWithIndex
-          .map { case (e, i) => tla.or(e, tla.not(whenEqualTo(state, i))) }
+        val iteCases = assertions.zipAll(elseAssertions, ValEx(TlaBool(true)), ValEx(TlaBool(true)))
```
Comment (konnov) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala:53]: We could use `zip` instead of `zipAll`, since there is an assertion above.

**Review by konnov — APPROVED** [review]
Looks good! I can see how it was failing on expanding a set instead of keeping it tight.

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala (hunk 1 above)
Comment (rodrigo7491) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/CherryPick.scala:474]: Will do, thanks!

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala (hunk 3 above)
Comment (rodrigo7491) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala:53]: Can we? If `elseAssertions` is empty we have to use `zipAll`, no?

Comment (rodrigo7491) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala:53]: I don't think it is necessary. If `elseAssertions` is not empty `zipAll` does nothing, if it is empty it makes the second element of each tuple in `iteCases` be `ValEx(TlaBool(true))`. If you think it would be good to explicitly populate `elseAssertions` with `assertions.size` copies of `ValEx(TlaBool(true))` an then use `zip` to make clearer what is happening I could do it.

Comment (rodrigo7491) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/rules/aux/IntOracle.scala:53]: Maybe adding a comment would be enough.
