### PR TITLE
Handle heap memory exhaustion gracefully

### LINKED ISSUE #466: [FEATURE] Add a friendly message on out of memory error
Now Apalache crashes with a stack trace when JVM runs out of memory. We should add a friendly explanation and point the user to hints about increasing memory limits, changing the tuning options, etc.

### PR DESCRIPTION
**Pull request by thpani**
Handle `java.lang.OutOfMemoryError` (i.e., out of heap memory) gracefully:

* Refactor exception adapters to accept `Throwable` ➞ [0cd916f](https://github.com/informalsystems/apalache/pull/1711/commits/0cd916f33fa8e22d3b2928c170d0413eba6fe570)
  (`OutOfMemoryError` derives from `Error`, not `Exception`)
* Add cases to the exception adapters ➞ [7ccc716](https://github.com/informalsystems/apalache/pull/1711/commits/7ccc716dd063b4bfcce27642cfdf9aa73a12d592)
* Add an early catch handler for when logging and injection aren't set up yet ➞ [3236762](https://github.com/informalsystems/apalache/pull/1711/commits/3236762e76ec5b2cf1afa9f327e2a6efe980b51e)

Fixes #466

### CODE REVIEW

File: mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala [hunk 1]
```diff
@@ -45,7 +45,18 @@ object Tool extends LazyLogging {
    *   the command line arguments
    */
   def main(args: Array[String]): Unit = {
-    System.exit(run(args))
+    try {
+      System.exit(run(args))
+    } catch {
+      case _: OutOfMemoryError =>
+        // We're usually catching this in `handleExceptions` below.
```
Comment (Kukovec) [inline mod-tool/src/main/scala/at/forsyte/apalache/tla/Tool.scala:52]:
```suggestion
        // We usually catch this in `handleExceptions` below.
```

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala [hunk 2]
```diff
@@ -28,7 +28,14 @@ class CheckerExceptionAdapter @Inject() (sourceStore: SourceStore, changeListene
...
   private lazy val ISSUES_LINK: String = "[https://github.com/informalsystems/apalache/issues]"
 
-  override def toMessage: PartialFunction[Exception, ErrorMessage] = {
+  override def toMessage: PartialFunction[Throwable, ErrorMessage] = {
+    // system issues
+    case err: OutOfMemoryError =>
+      logger.error(s"Ran out of heap memory (max JVM memory: ${Runtime.getRuntime.maxMemory})")
+      logger.error(s"To increase available heap memory, see the manual:")
+      logger.error("  [https://apalache.informal.systems/docs/apalache/running.html#supplying-jvm-arguments]")
+      NormalErrorMessage(s"Ran out of heap memory: ${err.getMessage}")
```
Comment (Kukovec) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala:37]: The body of this `case` seems to repeat 3 times in this PR, can you make an aux method call for this?

Comment (thpani) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala:37]: Actually, let me just provide that in the parent trait...

Comment (Kukovec) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala:37]: In the context of [this](https://apalache.informal.systems/docs/adr/007adr-restructuring.html), it feels like an `apa-base/glue` method, but practically, probably `tla-types` or even `lir`

Comment (Kukovec) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala:37]: Yeah, in the trait is probably easiest, didn't even notice they all inherit the same

Comment (thpani) [reply tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala]: Addressed in [493260d](https://github.com/informalsystems/apalache/pull/1711/commits/493260d548d9e422f4360219c436f4006222535f)

**Review by Kukovec — APPROVED** [review]
