### PR TITLE
Reordered assignments

### LINKED ISSUE #157: [BUG] Out of order assignments
Something has changed in the behavior of the assignment finder and type checker between 0.6.0 and unstable.

Now the following test fails:

```bash
cd $HOME/devl/apalache-tests/performance/bcastByz
$HOME/devl/apalache/bin/apalache-mc check --length=1 \
  --init=IndInv_Unforg_NoBcast --inv=IndInv_Unforg_NoBcast --cinit=ConstInit4 APAbcastByz.tla
```

Apalache fails with the message:

```
Step 0, level 0: checking if 1 transition(s) are enabled and violate the invariant I@15:55:37.782
APAbcastByz.tla:182:6-182:36, '(...), type error: Failed to find type of variable sent' E@15:55:37.798
APAbcastByz.tla:182:6-182:36, =(...), type error: Expected a Boolean, found: None E@15:55:37.803
APAbcastByz.tla:183:34-183:50, '(...), type error: Failed to find type of variable sent' E@15:55:37.808
APAbcastByz.tla:183:15-183:54, [S -> T](...), type error: Expected a finite set, found: None E@15:55:37.811
The outcome is: Error                                             I@15:55:37.843
Checker has found an error                                        I@15:55:37.843
It took me 0 days  0 hours  0 min  2 sec                          I@15:55:37.846
Total time: 2.121 sec                                             I@15:55:37.846
EXITCODE: OK
```

The reason for that is that `sent'` is assigned a value after it is used:

```tla
Init$0 ==
  (BMC!Skolem((\E t_18$1 \in [Corr -> { "V0", "V1", "SE", "AC" }]: pc' <- t_18$1))
      /\ Corr \in SUBSET (Corr \union Faulty)
      /\ Faulty \in SUBSET (Corr \union Faulty)
      /\ BMC!Skolem((\E t_1b$1 \in SUBSET ({
        <<t_19$1, t_1a$1>>:
          t_19$1 \in Corr \union Faulty,
          t_1a$1 \in {"ECHO"}
      }):
        sent' = t_1b$1))
      /\ BMC!Skolem((\E t_1e$1 \in [Corr
        -> SUBSET (sent'
          \union { <<t_1c$1, t_1d$1>>: t_1c$1 \in Faulty, t_1d$1 \in {"ECHO"} })]:
        rcvd' <- t_1e$1)))
    /\ sent' <- ({} <: {<<Int, STRING>>})
    /\ pc' = [ i$1 \in Corr |-> "V0" ]
```

We have been discussing for some time that the assignment finder should change the order of subformulas so that the assignments always come first. For some reason, the assignment finder always picks the assignment under the existential,
even if we swap the subformulas.

### LINKED ISSUE #338: [BUG] Operators in Init are not inlined before priming
This is a recent bug introduced in the refactoring 57d95aefcbcbf992079a662cd54fd970ea8e7ae7.

If `Init` is using another operator `Foo`, then the state variables inside `Foo` are not replaced with their primed versions.

Jure @Kukovec will add an integration test and fix the bug :-)

### PR DESCRIPTION
**Pull request by Kukovec**
closes #157 
closes #338

### CODE REVIEW

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala [hunk 1]
```diff
@@ -0,0 +1,50 @@
...
+import at.forsyte.apalache.tla.lir.{LetInEx, OperEx, TlaEx, TlaOperDecl}
+import at.forsyte.apalache.tla.lir.transformations.{TlaExTransformation, TransformationTracker}
+
+class Reordering[T]( ord : Ordering[T], rankingFn : TlaEx => T, tracker : TransformationTracker ) {
+
+  def reorder : TlaExTransformation = tracker.track {
+    // For now, only /\ and \/ are reordered, but the same process works for all commutative operators
+    case ex@OperEx( op@( TlaBoolOper.and | TlaBoolOper.or ), args@_* ) =>
+      val reorderedArgs = args.sortBy( rankingFn )( ord ) map reorder
+      if ( args == reorderedArgs ) ex
```
Comment (shonfeder) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:13]: What's the purpose of this check? iiuc, whenever `args == reorderedArgs` it will also be true that `ex == OperEx( op, reorderedArgs : _* )`. Right? So can skip the conditional here and on 18 and just return the constructed `OperEx` in the `else`?

The motive here (in addition to possibly removing unnecessary code) is the assumption that it's cheaper to just construct a new `OperEx` than to check all the arguments for equality.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala [hunk 2]
```diff
@@ -0,0 +1,50 @@
...
+    case ex@LetInEx( letInBody, defs@_* ) =>
+      val newDefs = defs map {
+        // Assignments can only appear in nullary operators
+        case TlaOperDecl( name, Nil, declBody ) =>
+          TlaOperDecl( name, Nil, reorder( declBody ) )
+        case d => d
+      }
+      val newBody = reorder( letInBody )
+      if ( defs == newDefs && letInBody == newBody ) ex
+      else LetInEx( newBody, newDefs : _* )
```
Comment (shonfeder) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:30]: Same question here about why we bother with the equality check.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala [hunk 3]
```diff
@@ -0,0 +1,50 @@
...
+
+
+    case ex => ex
+
+  }
+}
+
+object Reordering {
+
+  // The order we want, for x < y, is Some(x) < Some(y) < None
```
Comment (shonfeder) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:40]: Perhaps add a note here indicating why we want this ordering?

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala [hunk 4]
```diff
@@ -247,12 +255,32 @@ class SymbTransGenerator( tracker : TransformationTracker ) {
...
-      selections( ex.ID ).map( s =>
-        (
-          mkOrdered( s, strategy ),
-          sliceWith( s, selections )( ex )
-        )
-      ).toSeq
+      selections( ex.ID ).map { s =>
+        val ordered = mkOrdered( s, strategy )
+        def rankingFn( tlaEx: TlaEx) : Option[Int] = {
+          // the union of all sets in selections( tlaEx.ID ) lists all the assignments below
```
Comment (shonfeder) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala:261]: What is it that we are `below` here?

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala [hunk 5]
```diff
@@ -247,12 +255,32 @@ class SymbTransGenerator( tracker : TransformationTracker ) {
                         strategy : StrategyType,
                         selections : SelMapType
                       ) : Seq[SymbTrans] =
-      selections( ex.ID ).map( s =>
-        (
-          mkOrdered( s, strategy ),
-          sliceWith( s, selections )( ex )
-        )
-      ).toSeq
+      selections( ex.ID ).map { s =>
```
Comment (shonfeder) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala:258]: This block is pretty hairy. Do there's an relatively way way of refactoring this a bit so that the reader doesn't have to grok so much activity within this lambda? Perhaps by breaking it into a few named functions (for the sake of self-documentation) or at least one named function defined prior to actually calling the function on the selections?

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala [hunk 6]
```diff
@@ -19,14 +19,18 @@ import com.typesafe.scalalogging.LazyLogging
...
-      extends PrimingPass with LazyLogging {
+  extends PrimingPass with LazyLogging {
   /**
     * The name of the pass
     *
     * @return the name associated with the pass
     */
   override def name: String = "PrimingPass"
 
+  private def trSeq( seq: Seq[TlaExTransformation] ) : TlaExTransformation = {
```
Comment (shonfeder) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala:30]: Assuming `tr` is short for `translate`, using the full word would help with readability imo.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala [hunk 7]
```diff
@@ -0,0 +1,50 @@
+package at.forsyte.apalache.tla.assignments
+
+import at.forsyte.apalache.tla.lir.oper.TlaBoolOper
+import at.forsyte.apalache.tla.lir.{LetInEx, OperEx, TlaEx, TlaOperDecl}
+import at.forsyte.apalache.tla.lir.transformations.{TlaExTransformation, TransformationTracker}
+
+class Reordering[T]( ord : Ordering[T], rankingFn : TlaEx => T, tracker : TransformationTracker ) {
+
+  def reorder : TlaExTransformation = tracker.track {
```
Comment (shonfeder) [inline tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:9]: Seems like we might benefit from a unit test or two for this method. Does that seem reasonable?

**Review by shonfeder — COMMENTED** [review]
I left some feedback! I'm mainly reading for my own comprehension. My few suggestions are mostly just things I think might help me with readability, and are arguably just stylistic, so feel free to ignore (naturally ;)).

I do have two substantive question: the one about why the spec used for the integration test is so long, and the one about the seemingly redundant equality checks.

File: test/tla/APAbcastByz.tla [hunk 8]
```diff
@@ -0,0 +1,1072 @@
+------------------------------ MODULE APAbcastByz ------------------------------
```
[the remark this answers is not in the document]
Comment (Kukovec) [reply test/tla/APAbcastByz.tla:1]: Possibly, but Igor explicitly requested I include this one.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala [hunk 9]
```diff
@@ -0,0 +1,50 @@
...
+    // For now, only /\ and \/ are reordered, but the same process works for all commutative operators
```
[the remark this answers is not in the document]
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:10]: No plans atm, the only other control-flow relevant operator I can think of is `CASE`, which is commutative in base TLA+, but not actually commutative in Apalache. 
The opposite actually, it might happen that we end up not reordering `\/`. But for now, no TODO, this is complete as is.

File: test/tla/APAbcastByz.tla [hunk 10]
```diff
@@ -0,0 +1,1072 @@
...
+   example, additional constraints are  relationships between the number of messages, pc, and 
+   the number of faulty processes.    
+ *)                
+IndInv_Unforg_NoBcast ==  
+  /\ TypeOK
+  \*/\ FCConstraints
+  /\ sent = {} <: {MT}
+  /\ pc = [ i \in Corr |-> "V0" ]
+
+IndInv_Unforg_NoBcast4 ==
```
[the remark this answers is not in the document]
Comment (Kukovec) [reply test/tla/APAbcastByz.tla:238]: That's Igor's spec from the apalache-tests repository, I didn't write or edit it in any way, so I'll defer to @konnov.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala (hunk 1 above)
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:13]: This is a canonical check, in practice, it is better to not introduce a new expression not for performance's sake, but because preserving the expression also preserves the UID. This matters, because a lot of auxiliary information is passed as a `UID -> X` map, so by keeping the expression whenever possible, you don't invalidate those maps.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala [hunk 11]
```diff
@@ -0,0 +1,50 @@
+package at.forsyte.apalache.tla.assignments
+
+import at.forsyte.apalache.tla.lir.oper.TlaBoolOper
+import at.forsyte.apalache.tla.lir.{LetInEx, OperEx, TlaEx, TlaOperDecl}
+import at.forsyte.apalache.tla.lir.transformations.{TlaExTransformation, TransformationTracker}
+
+class Reordering[T]( ord : Ordering[T], rankingFn : TlaEx => T, tracker : TransformationTracker ) {
```
[the remark this answers is not in the document]
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:7]: I figured this class was tiny enough, but sure, can do.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala (hunk 4 above)
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala:261]: Below in the syntax-tree sense, i.e. subexpressions.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala (hunk 5 above)
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala:258]: If you want, sure, should be easy enough to split.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala (hunk 6 above)
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala:30]: `tr` is standard shorthand for `transform`, as in apply a `TlaExTransformation`. But sure, easy to rename.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala (hunk 7 above)
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:9]: I can add some, but this entire class is basically just boilerplate around line 12.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala (hunk 11 above)
[the remark this answers is not in the document]
Comment (shonfeder) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:7]: Yeah, the class is tiny enough that it's clear what its doing. But for a reader without the full context (which most will be) there's no clear indication of *why* this would need to be done, imo. Just a line or two indicating why we need a reordering class should be enough of a pointer for future readers I think.

File: test/tla/APAbcastByz.tla (hunk 10 above)
[the remark this answers is not in the document]
Comment (shonfeder) [reply test/tla/APAbcastByz.tla:238]: I see. In that case the content of this spec shouldn't really be part of the review I guess. Thanks :)

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala (hunk 7 above)
Comment (shonfeder) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:9]: You're definitely a better judge than I am of where unit tests would be applicable, but it does seem to me intuitively that we should have *some* kind of unit tests to ensure the reordering is happening as we expect. Does that seem sensible?

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala (hunk 6 above)
Comment (shonfeder) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala:30]: Ah! Where is this standardized? I'm not familiar but would interesting to learn the context :)

Given the amount of meanings for `tr` recorded by [wiktionary](https://en.wiktionary.org/wiki/tr.), I think the disambiguation is probably worth a few extra characters :)

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala (hunk 5 above)
Comment (shonfeder) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala:258]: I know it would help with readability for me. I suspect it'd help future readers too.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala (hunk 4 above)
Comment (shonfeder) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/SymbTransGenerator.scala:261]: Ah! How about:

```suggestion
          // the union of all sets in selections( tlaEx.ID ) lists all the assignments in the subexpressions of TlaEx
```

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala (hunk 1 above)
Comment (shonfeder) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:13]: Ah! I see thanks for explaining :)

In that case, would it be valid to preserve the UUID even when we reorder the args? Or does that break the logic we need for the expression identification?

File: test/tla/cli-integration-tests.md [hunk 12]
```diff
@@ -421,6 +421,16 @@ The outcome is: NoError
 ...
 ```
 
+### check APAbcastByz.tla succeeds
+
```
[the remark this answers is not in the document]
Comment (shonfeder) [reply test/tla/cli-integration-tests.md:425]: @konnov perhaps this would also be a good place to document why we want to test this complicated spec specifically? Perhaps you could provide the context needed for that?

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala (hunk 6 above)
Comment (shonfeder) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/passes/PrimingPassImpl.scala:30]: Duh. nm here. I finally our point about the relation between `tr` and the type. Sorry for being dense here. I think that should suffice for someone reading more carefully than I have here :)

File: test/tla/APAbcastByz.tla (hunk 10 above)
[the remark this answers is not in the document]
Comment (konnov) [reply test/tla/APAbcastByz.tla:238]: What we can do. Shorten the spec by removing the long header and THEOREMs and refer to the full spec: https://github.com/informalsystems/apalache-tests/blob/master/performance/bcastByz/APAbcastByz.tla

File: test/tla/cli-integration-tests.md (hunk 12 above)
[the remark this answers is not in the document]
Comment (konnov) [reply test/tla/cli-integration-tests.md:425]: Let's give a link to https://github.com/informalsystems/apalache/issues/157

**Review by konnov — COMMENTED** [review]
@shonfeder has already done the hard work of reviewing this PR. The rest looks good to me, just a few comments.

File: tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala (hunk 1 above)
Comment (Kukovec) [reply tla-assignments/src/main/scala/at/forsyte/apalache/tla/assignments/Reordering.scala:13]: I would advise against that, UIDs are, by definition, unique, and copying them over opens us up to a host of new, potentially very well hidden, bugs.
