### PR TITLE
Misc. bugfixes

### LINKED ISSUE #540: [BUG] at.forsyte.apalache.tla.bmcmt.RewriterException: Trying to expand a set of functions. This will blow up the solver.
- `Expand.tla`
```tla
--------------------------- MODULE Expand ----------------------------

EXTENDS Integers, FiniteSets

CONSTANT ChainIds
CONSTANT MaxClientsPerChain
CONSTANT MaxClientHeight

VARIABLE chains

ClientIds == 0..(MaxClientsPerChain - 1)
ClientHeights == 1..MaxClientHeight
NullHeight == 0

Clients == [
    ClientIds -> ClientHeights \union {NullHeight}
]
Chain == [
    clientIdCounter: 0..MaxClientsPerChain,
    clients: Clients
]

Init ==
    LET emptyChain == [
        clients |-> [clientId \in ClientIds |-> NullHeight],
        clientIdCounter |-> 0
    ] IN
    /\ chains = [chainId \in ChainIds |-> emptyChain]

Next == UNCHANGED <<chains>>

TypeOK == chains \in [ChainIds -> Chain]

=============================================================================
```

- `Expand.cfg`
```tla
CONSTANTS
    ChainIds = {"chain-A", "chain-B"}
    MaxClientsPerChain = 4
    MaxClientHeight = 4

INIT Init
NEXT Next

INVARIANT TypeOK
```

If I run `apalache-mc check Expand.tla` I get the following:

```
# APALACHE version 0.9.1-SNAPSHOT build v0.9.0-14-gb3faa66
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Checker options: filename=Expand.tla, init=, next=, inv=          I@14:43:04.515
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/vitor.enes/bin/apalache-pkg-0.9.1-SNAPSHOT-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tuning:                                                           I@14:43:04.732
PASS #0: SanyParser                                               I@14:43:04.732
Parsing file /home/vitor.enes/ibc-rs/modules/tests/support/model_based/Expand.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
PASS #1: ConfigurationPass                                        I@14:43:04.966
  > Expand.cfg: Loading TLC configuration                         I@14:43:04.967
  > Using the init predicate Init from the TLC config             I@14:43:05.025
  > Using the next predicate Next from the TLC config             I@14:43:05.025
  > Expand.cfg: found INVARIANTS: TypeOK                          I@14:43:05.025
  > Set the initialization predicate to Init                      I@14:43:05.028
  > Set the transition predicate to Next                          I@14:43:05.028
  > Set an invariant to TypeOK                                    I@14:43:05.029
  > Replaced CONSTANT ChainIds with {"chain-A", "chain-B"}        I@14:43:05.030
  > Replaced CONSTANT MaxClientsPerChain with 4                   I@14:43:05.032
  > Replaced CONSTANT MaxClientHeight with 4                      I@14:43:05.032
PASS #2: UnrollPass                                               I@14:43:05.051
  > Unroller                                                      I@14:43:05.065
PASS #3: PrimingPass                                              I@14:43:05.076
  > Introducing InitPrimed for Init'                              I@14:43:05.078
PASS #4: CoverAnalysisPass                                        I@14:43:05.090
PASS #5: InlinePass                                               I@14:43:05.090
  > InlinerOfUserOper                                             I@14:43:05.093
  > LetInExpander                                                 I@14:43:05.095
  > InlinerOfUserOper                                             I@14:43:05.095
Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next, TypeOK I@14:43:05.096
PASS #6: VCGen                                                    I@14:43:05.101
  > Producing verification conditions from the invariant TypeOK   I@14:43:05.101
  > VCGen produced 1 verification condition(s)                    I@14:43:05.102
PASS #7: PreprocessingPass                                        I@14:43:05.108
  > Before preprocessing: unique renaming                         I@14:43:05.108
 > Applying standard transformations:                             I@14:43:05.112
  > Desugarer                                                     I@14:43:05.113
  > PrimePropagation                                              I@14:43:05.121
  > UniqueRenamer                                                 I@14:43:05.128
  > Normalizer                                                    I@14:43:05.136
  > Keramelizer                                                   I@14:43:05.141
  > After preprocessing: UniqueRenamer                            I@14:43:05.150
PASS #8: TransitionFinderPass                                     I@14:43:05.160
  > Found 1 initializing transitions                              I@14:43:05.172
  > Found 1 transitions                                           I@14:43:05.174
  > No constant initializer                                       I@14:43:05.174
  > Applying unique renaming                                      I@14:43:05.175
PASS #9: OptimizationPass                                         I@14:43:05.181
 > Applying optimizations:                                        I@14:43:05.183
  > ConstSimplifier                                               I@14:43:05.184
  > ExprOptimizer                                                 I@14:43:05.185
  > ConstSimplifier                                               I@14:43:05.186
PASS #10: AnalysisPass                                            I@14:43:05.190
 > Marking skolemizable existentials and sets to be expanded...   I@14:43:05.191
  > SkolemizationMarker                                           I@14:43:05.191
  > ExpansionMarker                                               I@14:43:05.192
The set [(0 .. 3) → ((1 .. 4) ∪ {0})] will be expanded. This will blow up the solver. W@14:43:05.194
The set [(0 .. 3) → ((1 .. 4) ∪ {0})] will be expanded. This will blow up the solver. W@14:43:05.195
 > Running analyzers...                                           I@14:43:05.196
  > Introduced expression grades                                  I@14:43:05.200
  > Introduced 0 formula hints                                    I@14:43:05.200
PASS #11: BoundedChecker                                          I@14:43:05.201
State 0: Checking 1 invariants                                    I@14:43:05.417
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],at.forsyte.apalache.tla.bmcmt.RewriterException: Trying to expand a set of functions. This will blow up the solver.)
Expand.tla:18:10-21:1: rewriter error: Trying to expand a set of functions. This will blow up the solver. E@14:43:05.425
at.forsyte.apalache.tla.bmcmt.RewriterException: Trying to expand a set of functions. This will blow up the solver.
        at at.forsyte.apalache.tla.bmcmt.rules.SetExpandRule.apply(SetExpandRule.scala:26)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:345)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:374)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:405)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.eachExpr$1(SymbStateRewriterImpl.scala:423)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.$anonfun$rewriteSeqUntilDone$1(SymbStateRewriterImpl.scala:429)
        at scala.collection.immutable.List.map(List.scala:297)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteSeqUntilDone(SymbStateRewriterImpl.scala:429)
        at at.forsyte.apalache.tla.bmcmt.rules.aux.MapBase.rewriteSetMapManyArgs(MapBase.scala:32)
        at at.forsyte.apalache.tla.bmcmt.rules.SetMapRule.apply(SetMapRule.scala:28)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:345)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:374)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:405)
        at at.forsyte.apalache.tla.bmcmt.rules.FunSetCtorRule.apply(FunSetCtorRule.scala:28)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:345)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:374)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:405)
        at at.forsyte.apalache.tla.bmcmt.rules.SetInRule.apply(SetInRule.scala:46)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:345)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:374)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:405)
        at at.forsyte.apalache.tla.bmcmt.rules.NegRule.apply(NegRule.scala:27)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:345)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:374)
        at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:405)
        at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.assertState(TransitionExecutorImpl.scala:197)
        at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.assertState(FilteredTransitionExecutor.scala:91)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$checkInvariants$2(SeqModelChecker.scala:206)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$checkInvariants$2$adapted(SeqModelChecker.scala:199)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.checkInvariants(SeqModelChecker.scala:199)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5(SeqModelChecker.scala:129)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5$adapted(SeqModelChecker.scala:105)
        at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:105)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:50)
        at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:30)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:108)
        at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:83)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:23)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:38)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:173)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:258)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  0 sec                          I@14:43:05.425
Total time: 0.912 sec                                             I@14:43:05.425
EXITCODE: ERROR (99)
```

**Desktop (please complete the following information):**
 - Debian GNU/Linux 10
 - openjdk 11.0.9.1 2020-11-04
 - APALACHE version 0.9.1-SNAPSHOT build v0.9.0-14-gb3faa66

### LINKED ISSUE #593: [BUG] java.lang.IllegalStateException: Found two different declarations with the same name
**To Reproduce**
- `IBC.tla`
```tla
--------------------------------- MODULE IBC ----------------------------------

EXTENDS Integers, FiniteSets, ICS02

VARIABLE action

Init ==
    /\ action = AsAction([type |-> "None"])

Next ==
    LET result == ICS02_CreateClient IN
    UNCHANGED <<action>>

===============================================================================
```

- `ICS02.tla`
```tla
------------------------------- MODULE ICS02 ----------------------------------

EXTENDS Integers, FiniteSets

(********************** TYPE ANNOTATIONS FOR APALACHE ************************)
\* operator for type annotations
a <: b == a

ActionType == [
    type |-> STRING
]
AsAction(a) == a <: ActionType
(******************* END OF TYPE ANNOTATIONS FOR APALACHE ********************)

ICS02_CreateClient ==
    LET action == AsAction([
        type |-> "ICS02CreateClient"
    ]) IN
    "X"

===============================================================================
```

The error should appear with the following:
```bash
$ apalache-mc check IBC.tla
```

**Log files**
```
# APALACHE version 0.10.1-SNAPSHOT build v0.10.0-21-ge2b7e41-dirty
#
# WARNING: This tool is in the experimental stage.
#          Please report bugs at: [https://github.com/informalsystems/apalache/issues]
# 
# Usage statistics is OFF. We care about your privacy.
# If you want to help our project, consider enabling statistics with config --enable-stats=true.

Checker options: filename=IBC.tla, init=, next=, inv=             I@12:07:34.072
WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.inject.internal.cglib.core.$ReflectUtils$1 (file:/home/vitor.enes/bin/apalache-pkg-0.10.1-SNAPSHOT-full.jar) to method java.lang.ClassLoader.defineClass(java.lang.String,byte[],int,int,java.security.ProtectionDomain)
WARNING: Please consider reporting this to the maintainers of com.google.inject.internal.cglib.core.$ReflectUtils$1
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations
WARNING: All illegal access operations will be denied in a future release
Tuning:                                                           I@12:07:34.295
PASS #0: SanyParser                                               I@12:07:34.296
Parsing file /home/vitor.enes/ibc-rs/modules/tests/support/model_based/IBC.tla
Parsing file /tmp/Integers.tla
Parsing file /tmp/FiniteSets.tla
Parsing file /home/vitor.enes/ibc-rs/modules/tests/support/model_based/ICS02.tla
Parsing file /tmp/Naturals.tla
Parsing file /tmp/Sequences.tla
(Please report an issue at: [https://github.com/informalsystems/apalache/issues],java.lang.IllegalStateException: Found two different declarations with the same name action: DeclUnit(TlaVarDecl(action)) and DeclUnit(TlaOperDecl(action,List(),AsAction(["type" ↦ "ICS02CreateClient"]))))
Unhandled exception                                               E@12:07:34.482
java.lang.IllegalStateException: Found two different declarations with the same name action: DeclUnit(TlaVarDecl(action)) and DeclUnit(TlaOperDecl(action,List(),AsAction(["type" ↦ "ICS02CreateClient"])))
        at at.forsyte.apalache.tla.imp.Context$ContextImpl$$anonfun$push$1.applyOrElse(Context.scala:167)
        at at.forsyte.apalache.tla.imp.Context$ContextImpl$$anonfun$push$1.applyOrElse(Context.scala:164)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:228)
        at scala.PartialFunction$Lifted.apply(PartialFunction.scala:224)
        at scala.Option.collect(Option.scala:432)
        at at.forsyte.apalache.tla.imp.Context$ContextImpl.push(Context.scala:164)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.$anonfun$translateLetIn$1(ExprOrOpArgNodeTranslator.scala:113)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.$anonfun$translateLetIn$1$adapted(ExprOrOpArgNodeTranslator.scala:107)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.translateLetIn(ExprOrOpArgNodeTranslator.scala:107)
        at at.forsyte.apalache.tla.imp.ExprOrOpArgNodeTranslator.translate(ExprOrOpArgNodeTranslator.scala:52)
        at at.forsyte.apalache.tla.imp.OpDefTranslator.translate(OpDefTranslator.scala:69)
        at at.forsyte.apalache.tla.imp.ModuleTranslator.$anonfun$translate$4(ModuleTranslator.scala:69)
        at at.forsyte.apalache.tla.imp.ModuleTranslator.$anonfun$translate$4$adapted(ModuleTranslator.scala:61)
        at scala.collection.immutable.List.foreach(List.scala:431)
        at at.forsyte.apalache.tla.imp.ModuleTranslator.translate(ModuleTranslator.scala:61)
        at at.forsyte.apalache.tla.imp.SanyImporter.$anonfun$loadFromFile$1(SanyImporter.scala:46)
        at scala.collection.IndexedSeqOptimized.foldLeft(IndexedSeqOptimized.scala:60)
        at scala.collection.IndexedSeqOptimized.foldLeft$(IndexedSeqOptimized.scala:68)
        at scala.collection.mutable.ArrayOps$ofRef.foldLeft(ArrayOps.scala:198)
        at at.forsyte.apalache.tla.imp.SanyImporter.loadFromFile(SanyImporter.scala:44)
        at at.forsyte.apalache.tla.imp.passes.SanyParserPassImpl.execute(SanyParserPassImpl.scala:56)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
        at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
        at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:173)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:258)
        at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
        at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
        at at.forsyte.apalache.tla.Tool.main(Tool.scala)
It took me 0 days  0 hours  0 min  0 sec                          I@12:07:34.483
Total time: 0.412 sec                                             I@12:07:34.483
EXITCODE: ERROR (99)
```

**Desktop (please complete the following information):**
 - Debian GNU/Linux 10
 - openjdk 11.0.9.1 2020-11-04
 - APALACHE version 0.10.1-SNAPSHOT build v0.10.0-21-ge2b7e41-dirty

### PR DESCRIPTION
**Pull request by Kukovec**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

closes #540 
Fixes UX from #593, but not the underlying cause.

### CODE REVIEW

File: tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala [hunk 1]
```diff
@@ -7,7 +7,7 @@ import at.forsyte.apalache.tla.imp.SanyException
 import at.forsyte.apalache.tla.imp.src.SourceStore
 import at.forsyte.apalache.tla.lir.storage.{ChangeListener, SourceLocator}
 import at.forsyte.apalache.tla.lir.{
-  LanguagePredError, MalformedTlaError, OperEx, OutdatedAnnotationsError, TypingException, UID
+  LanguagePredError, MalformedSepecificationError, MalformedTlaError, OutdatedAnnotationsError, TypingException, UID
```
Comment (konnov) [inline tla-bmcmt/src/main/scala/at/forsyte/apalache/tla/bmcmt/config/CheckerExceptionAdapter.scala:10]: MalformedSpecificationError

**Review by konnov — APPROVED** [review]
Very nice! Are you sure that #593 is fixed now? The issue is that under some conditions you can define two operators of the same name.

**Comment by Kukovec** [comment]
> 
> 
> Very nice! Are you sure that #593 is fixed now? The issue is that under some conditions you can define two operators of the same name.

This PR does not address whether or not an exception should be raised there, what it does is present the error message in a user-readable way. Having multiple declarations with the same name sounds like it should cause an exception anyhow.
