### PR TITLE
close #582, close #583

### LINKED ISSUE #582: [FEATURE] Type inference for recursive functions of multiple arguments
The current version crashes on recursive functions of more than one argument

### LINKED ISSUE #583: [FEATURE] Support for pattern matching in recursive functions
The syntax of TLA+ allows one to write the following definition:

```tla
fun[<<a, b>> \in Int \X BOOLEAN] == a
```

The type checker should be able to check it correctly.

### PR DESCRIPTION
**Pull request by konnov**
This PR closes two related issues #582 and #583. That is, support for recursive functions of multiple arguments in the type checker.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

### CODE REVIEW

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala [hunk 1]
```diff
@@ -627,23 +627,59 @@ class ToEtcExpr(annotationStore: AnnotationStore, varPool: TypeVarPool) extends
...
-      case OperEx(TlaFunOper.recFunDef, body, NameEx(name), bindingSet) =>
-        // the expected type is: (((a -> b) => (a => b)) => (a -> b)) (λ $recFun ∈ Set(c -> d). λ x ∈ Int. x)
+      case OperEx(TlaFunOper.recFunDef, body, args @ _*) =>
+        // fun[x \in S, y \in T |-> e] == ...
+        // or, fun[<<x, y>> \in S, z \in T |-> e] == ...
+        //
+        // The expected type is for a one-argument function is:
+        // (((b -> a) => (b => a)) => (b -> a)) (λ $recFun ∈ Set(c -> d). λ x ∈ Int. x)
+        //
+        // (The case of multiple arguments is quite complex)
```
Comment (shonfeder) [inline tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala:637]: Is this comment meant to say something about the code on line 638 or meant to explain why there's not a comment giving the type for a multiple argument function?

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala [hunk 2]
```diff
@@ -627,23 +627,59 @@ class ToEtcExpr(annotationStore: AnnotationStore, varPool: TypeVarPool) extends
...
+                }
+                .toSeq: _*
+          )
+
         val a = varPool.fresh
-        val b = varPool.fresh
-        val funType = FunT1(a, b)
-        val aToB = OperT1(Seq(a), b)
-        val principal = OperT1(Seq(OperT1(Seq(funType), aToB)), funType)
+        // start with "b", as "a" goes to the result
```
Comment (shonfeder) [inline tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala:650]: I'm afraid this this comment might not be very clear to other readers. It's not at all obvious how are we starting with `b`, since `b` doesn't appear here.

Should `a` perhaps be called `resultType`? That would make half this comment unnecessary.

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala [hunk 3]
```diff
@@ -627,23 +627,59 @@ class ToEtcExpr(annotationStore: AnnotationStore, varPool: TypeVarPool) extends
...
+        val typeVars = varPool.fresh(bindings.length)
```
Comment (shonfeder) [inline tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala:651]: We could call this `argTypes`.

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala [hunk 4]
```diff
@@ -627,23 +627,59 @@ class ToEtcExpr(annotationStore: AnnotationStore, varPool: TypeVarPool) extends
...
+          mkAbs(ExactRef(body.ID), this(body), bindings: _*)
+        // create another vector of type variables for the lambda over a function
+        val recFunResTypeVar = varPool.fresh
+        // similar to funFrom
+        val recFunFrom = varPool.fresh(bindings.length) match {
+          // With one argument, the generated function has the type d -> c, that is, no tuple is involved.
+          case Seq(one) => one
+          // With multiple arguments, the generated function has the type <<d, e>> -> c, that is, it accepts a tuple
+          case many => TupT1(many: _*)
+        }
```
Comment (shonfeder) [inline tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala:676]: Seems like this is general enough it should be its own auxiliary function. Then you wouldn't have to repeat the comments :)

**Review by shonfeder — APPROVED** [review]

**Comment by shonfeder** [comment]
LGTM, whether or not you find my suggestions worth taking on :)

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala (hunk 1 above)
Comment (konnov) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala:637]: It was referring to the case above, which is only single argument

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala (hunk 2 above)
Comment (konnov) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/ToEtcExpr.scala:650]: that sounds good :)

**Comment by konnov** [comment]
Thanks for the comments @shonfeder ! The code definitely has improved.
