### PR TITLE
Fixes JSON deserialization

### LINKED ISSUE #1281: [BUG] Generated JSON IR is not parsed back
## Description

Json-file generated with `parse` command is not parsed.

## Input specification

```
---- MODULE D ----

VARIABLE 
    \* @type: Bool;
    x
Spec == x \in BOOLEAN

====
```

## The command line parameters used to run the tool

Two steps:
1) java -cp apalache.jar  parse --output=D.json D.tla
2) java -cp apalache.jar  parse D.json

## Expected behavior

D.json is successfully parsed

## Log files

```
12:08:02.224 [main] INFO  a.f.a.t.Tool$ - Parse D.json
12:08:02.224 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
12:08:02.297 [main] ERROR a.f.a.t.i.p.SanyParserPassImpl -   > '(' expected but record field 'Untyped' found
12:08:02.297 [main] ERROR a.f.a.t.i.p.SanyParserPassImpl -   > Error parsing file C:\work\TLA\apalache\D.json
12:08:02.297 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [FAIL]
12:08:02.297 [main] INFO  a.f.a.t.Tool$ - Parser has failed
12:08:02.298 [main] INFO  a.f.a.t.Tool$ - It took me 0 days  0 hours  0 min  0 sec
12:08:02.298 [main] INFO  a.f.a.t.Tool$ - Total time: 0.448 sec
```
## System information

- Apalache version [`apalache-mc version`]: 0.19.3 build 52f9fe2
- OS: Ubuntu Linux 20.04
- JDK version: OpenJDK Runtime Environment Zulu17.28+13-CA

### PR DESCRIPTION
**Pull request by Kukovec**
- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] Documentation added for any new functionality
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

Previously, the JSON decoder was expecting fully-typed JSON files. Consequently, it was unable to consume Apalache output produced by, e.g. `parse`, since that produces `Untyped` JSON IR. This patch relaxes the requirements on input-JSON: "type" : "Untyped" maps to `Untyped()`, as one would expect, instead of throwing. Using JSON as input for model checking still requires an OK from Snowcat after parsing, so this is not an issue.
 
Also adds more tests and fixes for `TLaPredefSets`, which were excluded from JSON encodings for some inexplicable reason.

Additionally, this PR moves `TlaType1Gen` to tla-ir to enable IR generators producing types of the type `TlaType1`.

Closes #1281.
@konnov , is #1282 still relevant with these changes?

### CODE REVIEW

**Review by shonfeder — APPROVED** [review]

File: tla-io/src/main/scala/at/forsyte/apalache/io/lir/TlaType1TagPrinter.scala [hunk 1]
```diff
@@ -7,6 +7,9 @@ class TlaType1TagPrinter extends TypeTagPrinter {
     tag match {
       case Untyped()           => "Untyped"
       case Typed(tt: TlaType1) => tt.toString
+      // IrGenerators generates type with arbitrary integers. In order not to crash JSON (en|de)coding tests,
+      // we need to not throw on this variant of Typed, but we erase the type with Untyped()
+      case Typed(_: Int) => "Untyped"
       // unexpected type, output as much as we can
       case Typed(_) => "Typed[%s](%s)".format(tag.getClass.getSimpleName, tag)
     }
```
Comment (konnov) [inline tla-io/src/main/scala/at/forsyte/apalache/io/lir/TlaType1TagPrinter.scala:15]: Why is this class called `TlaType1TagPrinter`, though it is printing arbitrary `Untyped()` as well? Shall we rename it to `TagPrinter`?

**Review by konnov — APPROVED** [review]
Look great! Just one comment on the class name

File: tla-io/src/main/scala/at/forsyte/apalache/io/lir/TlaType1TagPrinter.scala (hunk 1 above)
Comment (Kukovec) [reply tla-io/src/main/scala/at/forsyte/apalache/io/lir/TlaType1TagPrinter.scala:15]: I guess if we're sticking to the pattern, `DefaultTagPrinter`
