### PR TITLE
Fixing DeclarationSorter

### LINKED ISSUE #758: [BUG] Type annotations in MC_*.tla files
## Description

I have a module, let's call it `Spec.tla` and a module `MC_Spec.tla` which instantiates `Spec.tla`. I would like to use `MC_Spec.tla` to run model checking with Apalache. The variables in both modules are annotated, and so are the constants in `Spec.tla`. Most of the annotations use type aliases, which are defined in a third module, `Spec_Definitions.tla`. Running the type checker on `Spec.tla` says that the types are great, but on `MC_Spec.tla`, it complains that an already annotated operator is undefined. 

## Input specification

[IBCCore.tla](https://github.com/informalsystems/ibc-rs/blob/ilina/running_apalache/docs/spec/tla/ibc-core/IBCCore.tla)
[MC_IBCCore.tla](https://github.com/informalsystems/ibc-rs/blob/ilina/running_apalache/docs/spec/tla/ibc-core/MC_IBCCore.tla)

## The command line parameters used to run the tool
```
 apalache-mc typecheck IBCCore.tla
```
and 
```
 apalache-mc typecheck MC_IBCCore.tla
```

## Expected behavior

No errors for `MC_IBCCore.tla`.

## Log files

`apalache-mc typecheck IBCCore.tla`
  - detailed.log
 ```
 17:15:13.458 [main] INFO  a.f.a.t.Tool$ - Type checking IBCCore.tla
17:15:13.766 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
17:15:15.376 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
17:15:15.377 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
17:15:15.377 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
17:15:15.507 [main] DEBUG a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > JSON output: /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/x/17.15-20.04.2021-5746884103650158326/out-pre-TypeCheckerSnowcat.json
17:15:18.443 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Your types are great!
17:15:18.443 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > All expressions are typed
17:15:18.827 [main] DEBUG a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > JSON output: /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/x/17.15-20.04.2021-5746884103650158326/out-post-TypeCheckerSnowcat.json
17:15:18.828 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [OK]
17:15:18.829 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #2: Terminal
17:15:18.829 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #2: Terminal [OK]
17:15:18.829 [main] INFO  a.f.a.t.Tool$ - Type checker [OK]
17:15:18.830 [main] INFO  a.f.a.t.Tool$ - It took me 0 days  0 hours  0 min  5 sec
17:15:18.831 [main] INFO  a.f.a.t.Tool$ - Total time: 5.375 sec

 ```
 - command line output:
 ```
 Type checking IBCCore.tla                                         I@17:15:13.458
PASS #0: SanyParser                                               I@17:15:13.766
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/IBCCore.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Integers.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/FiniteSets.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Sequences.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/IBCCoreDefinitions.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Naturals.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS18Relayer.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/Chain.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS02ClientHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS03ConnectionHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS04ChannelHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS04PacketHandlers.tla
PASS #1: TypeCheckerSnowcat                                       I@17:15:15.377
 > Running Snowcat .::.                                           I@17:15:15.377
 > Your types are great!                                          I@17:15:18.443
 > All expressions are typed                                      I@17:15:18.443
PASS #2: Terminal                                                 I@17:15:18.829
Type checker [OK]                                                 I@17:15:18.829
It took me 0 days  0 hours  0 min  5 sec                          I@17:15:18.830
Total time: 5.375 sec                                             I@17:15:18.831
EXITCODE: OK
```

`apalache-mc typecheck MC_IBCCore.tla`
 - detailed.log
 ```
17:18:57.035 [main] INFO  a.f.a.t.Tool$ - Type checking MC_IBCCore.tla
17:18:57.283 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
17:18:59.016 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
17:18:59.017 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
17:18:59.017 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
17:18:59.117 [main] DEBUG a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > JSON output: /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/x/17.18-20.04.2021-999478169097429333/out-pre-TypeCheckerSnowcat.json
17:19:00.347 [main] ERROR a.f.a.t.t.p.LoggingTypeCheckerListener - [IBCCore.tla:430:29-430:49]: Undefined operator name E47084@GetChainByID. Introduce a type annotation.
17:19:00.348 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Snowcat asks you to fix the types. Meow.
17:19:00.348 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [FAIL]
17:19:00.348 [main] INFO  a.f.a.t.Tool$ - Type checker [FAILED]
17:19:00.349 [main] INFO  a.f.a.t.Tool$ - It took me 0 days  0 hours  0 min  3 sec
17:19:00.349 [main] INFO  a.f.a.t.Tool$ - Total time: 3.317 sec
 ```
 - command line output
 ```
Type checking MC_IBCCore.tla                                      I@17:18:57.035
PASS #0: SanyParser                                               I@17:18:57.283
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/MC_IBCCore.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/IBCCoreDefinitions.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Integers.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/FiniteSets.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Sequences.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Naturals.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/IBCCore.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS18Relayer.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/Chain.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS02ClientHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS03ConnectionHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS04ChannelHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS04PacketHandlers.tla
PASS #1: TypeCheckerSnowcat                                       I@17:18:59.017
 > Running Snowcat .::.                                           I@17:18:59.017
[IBCCore.tla:430:29-430:49]: Undefined operator name E47084@GetChainByID. Introduce a type annotation. E@17:19:00.347
 > Snowcat asks you to fix the types. Meow.                       I@17:19:00.348
Type checker [FAILED]                                             I@17:19:00.348
It took me 0 days  0 hours  0 min  3 sec                          I@17:19:00.349
Total time: 3.317 sec                                             I@17:19:00.349
EXITCODE: OK
 ```

## System information

- Apalache version: 0.15.2-SNAPSHOT build v0.15.1-4-gb68618c
- OS: Mac OS 11.2.3
- JDK version: Java SE Development Kit 1.8.0_261

### LINKED ISSUE #759: [BUG] Unhandled exception when running Apalache on IBCTokenTransfer.tla
## Description

Unhandled exception. 

## Input specification

[IBCTokenTransfer.tla](https://github.com/informalsystems/ibc-rs/blob/ilina/running_apalache/docs/spec/tla/fungible-token-transfer/IBCTokenTransfer.tla)  
[MC_IBCTokenTransfer.tla](https://github.com/informalsystems/ibc-rs/blob/ilina/running_apalache/docs/spec/tla/fungible-token-transfer/MC_IBCTokenTransfer.tla)

## The command line parameters used to run the tool

`apalache-mc check MC_IBCTokenTransfer.tla`

## Log files

detailed.log

```
18:20:29.988 [main] INFO  a.f.a.t.Tool$ - Checker options: filename=MC_IBCTokenTransfer.tla, init=, next=, inv=
18:20:30.279 [main] INFO  a.f.a.t.Tool$ - Tuning: 
18:20:30.279 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser
18:20:31.080 [main] WARN  a.f.a.t.i.ModuleTranslator - WORKAROUND #130: labelling operator Sum as recursive, though SANY did not tell us so.
18:20:31.600 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #0: SanyParser [OK]
18:20:31.600 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat
18:20:31.601 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Running Snowcat .::.
18:20:31.696 [main] DEBUG a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > JSON output: /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/fungible-token-transfer/x/18.20-20.04.2021-3253939048055245493/out-pre-TypeCheckerSnowcat.json
18:20:33.110 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > Your types are great!
18:20:33.111 [main] INFO  a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > All expressions are typed
18:20:33.382 [main] DEBUG a.f.a.t.t.p.EtcTypeCheckerPassImpl -  > JSON output: /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/fungible-token-transfer/x/18.20-20.04.2021-3253939048055245493/out-post-TypeCheckerSnowcat.json
18:20:33.383 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #1: TypeCheckerSnowcat [OK]
18:20:33.383 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass
18:20:33.386 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > MC_IBCTokenTransfer.cfg: Loading TLC configuration
18:20:33.390 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > No TLC configuration found. Skipping.
18:20:33.390 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --init is not set. Using Init
18:20:33.390 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Command line option --next is not set. Using Next
18:20:33.390 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the initialization predicate to Init
18:20:33.391 [main] INFO  a.f.a.t.p.p.ConfigurationPassImpl -   > Set the transition predicate to Next
18:20:33.463 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #2: ConfigurationPass [OK]
18:20:33.464 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass
18:20:33.464 [main] INFO  a.f.a.t.p.p.DesugarerPassImpl -   > Desugaring...
18:20:33.546 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #3: DesugarerPass [OK]
18:20:33.547 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #4: UnrollPass
18:20:33.605 [main] INFO  a.f.a.t.p.p.UnrollPassImpl -   > Unroller
18:20:33.822 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #4: UnrollPass [OK]
18:20:33.823 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #5: PrimingPass
18:20:33.826 [main] INFO  a.f.a.t.a.p.PrimingPassImpl -   > Introducing InitPrimed for Init'
18:20:33.886 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #5: PrimingPass [OK]
18:20:33.887 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #6: CoverAnalysisPass
18:20:33.887 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #6: CoverAnalysisPass [OK]
18:20:33.889 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #7: InlinePass
18:20:33.890 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > InlinerOfUserOper
18:20:34.074 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > LetInExpander
18:20:34.195 [main] INFO  a.f.a.t.p.p.InlinePassImpl -   > InlinerOfUserOper
18:20:34.214 [main] INFO  a.f.a.t.p.p.InlinePassImpl - Leaving only relevant operators: CInitPrimed, Init, InitPrimed, Next
18:20:34.252 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #7: InlinePass [OK]
18:20:34.253 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #8: VCGen
18:20:34.253 [main] INFO  a.f.a.t.b.p.VCGenPassImpl -   > No invariant given. Only deadlocks will be checked
18:20:34.288 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #8: VCGen [OK]
18:20:34.289 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #9: PreprocessingPass
18:20:34.289 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Before preprocessing: unique renaming
18:20:34.295 [main] INFO  a.f.a.t.p.p.PreproPassImpl -  > Applying standard transformations:
18:20:34.295 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > PrimePropagation
18:20:34.345 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Desugarer
18:20:34.406 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > UniqueRenamer
18:20:34.493 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Normalizer
18:20:34.562 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > Keramelizer
18:20:34.619 [main] INFO  a.f.a.t.p.p.PreproPassImpl -   > After preprocessing: UniqueRenamer
18:20:34.688 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #9: PreprocessingPass [OK]
18:20:34.688 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #10: TransitionFinderPass
18:20:34.830 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Found 1 initializing transitions
18:20:34.956 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Found 18 transitions
18:20:34.956 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > No constant initializer
18:20:34.957 [main] INFO  a.f.a.t.a.p.TransitionPassImpl -   > Applying unique renaming
18:20:35.026 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #10: TransitionFinderPass [OK]
18:20:35.026 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #11: OptimizationPass
18:20:35.029 [main] INFO  a.f.a.t.p.p.OptPassImpl -  > Applying optimizations:
18:20:35.030 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
18:20:35.066 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ExprOptimizer
18:20:35.091 [main] INFO  a.f.a.t.p.p.OptPassImpl -   > ConstSimplifier
18:20:35.161 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #11: OptimizationPass [OK]
18:20:35.161 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #12: AnalysisPass
18:20:35.163 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Marking skolemizable existentials and sets to be expanded...
18:20:35.164 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > SkolemizationMarker
18:20:35.168 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > ExpansionMarker
18:20:35.196 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -  > Running analyzers...
18:20:35.241 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Introduced expression grades
18:20:35.241 [main] INFO  a.f.a.t.b.p.AnalysisPassImpl -   > Introduced 51 formula hints
18:20:35.241 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #12: AnalysisPass [OK]
18:20:35.241 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #13: PostTypeCheckerSnowcat
18:20:35.241 [main] INFO  a.f.a.t.b.p.PostTypeCheckerPassImpl -  > Running Snowcat .::.
18:20:35.332 [main] DEBUG a.f.a.t.b.p.PostTypeCheckerPassImpl -  > JSON output: /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/fungible-token-transfer/x/18.20-20.04.2021-3253939048055245493/out-pre-PostTypeCheckerSnowcat.json
18:20:38.390 [main] INFO  a.f.a.t.b.p.PostTypeCheckerPassImpl -  > Your types are great!
18:20:38.391 [main] INFO  a.f.a.t.b.p.PostTypeCheckerPassImpl -  > All expressions are typed
18:20:38.468 [main] DEBUG a.f.a.t.b.p.PostTypeCheckerPassImpl -  > JSON output: /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/fungible-token-transfer/x/18.20-20.04.2021-3253939048055245493/out-post-PostTypeCheckerSnowcat.json
18:20:38.468 [main] DEBUG a.f.a.i.p.PassChainExecutor - PASS #13: PostTypeCheckerSnowcat [OK]
18:20:38.468 [main] INFO  a.f.a.i.p.PassChainExecutor - PASS #14: BoundedChecker
18:20:39.236 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #0, transition #0
18:20:39.236 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
18:20:39.337 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0. Is it enabled?
18:20:39.338 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 0: Transition #0 is enabled
18:20:39.343 [main] INFO  a.f.a.t.b.t.TransitionExecutorImpl - Step 0: picking a transition out of 1 transition(s)
18:20:39.352 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #0
18:20:39.352 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
18:20:39.363 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #0. Is it enabled?
18:20:39.363 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #0 is enabled
18:20:39.364 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #1
18:20:39.364 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
18:20:39.367 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #1. Is it enabled?
18:20:39.368 [main] DEBUG a.f.a.t.b.SeqModelChecker - Step 1: Transition #1 is enabled
18:20:39.368 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Step #1, transition #2
18:20:39.368 [main] DEBUG a.f.a.t.b.t.TransitionExecutorImpl - Translating to SMT...
18:20:39.570 [main] ERROR a.f.a.t.Tool$ - Unhandled exception
java.lang.IllegalStateException: Found inconsistent records in a set: Record["channelID" -> Const, "counterpartyChannelID" -> Const, "counterpartyPortID" -> Const, "order" -> Const, "portID" -> Const, "state" -> Const, "version" -> Const] and FinSet[Record["acknowledgement" -> Bool, "channelID" -> Const, "portID" -> Const, "sequence" -> Int]]
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.$anonfun$findCommonRecordType$1(CherryPick.scala:328)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.$anonfun$findCommonRecordType$1$adapted(CherryPick.scala:321)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.findCommonRecordType(CherryPick.scala:321)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickRecord(CherryPick.scala:219)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickByOracle(CherryPick.scala:123)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickAtPos$2(CherryPick.scala:245)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.$anonfun$pickRecord$5(CherryPick.scala:257)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickRecord(CherryPick.scala:257)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickByOracle(CherryPick.scala:123)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickAtPos$2(CherryPick.scala:245)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.$anonfun$pickRecord$5(CherryPick.scala:257)
	at scala.collection.TraversableLike.$anonfun$map$1(TraversableLike.scala:285)
	at scala.collection.Iterator.foreach(Iterator.scala:943)
	at scala.collection.Iterator.foreach$(Iterator.scala:943)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1431)
	at scala.collection.IterableLike.foreach(IterableLike.scala:74)
	at scala.collection.IterableLike.foreach$(IterableLike.scala:73)
	at scala.collection.AbstractIterable.foreach(Iterable.scala:56)
	at scala.collection.TraversableLike.map(TraversableLike.scala:285)
	at scala.collection.TraversableLike.map$(TraversableLike.scala:278)
	at scala.collection.AbstractTraversable.map(Traversable.scala:108)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickRecord(CherryPick.scala:257)
	at at.forsyte.apalache.tla.bmcmt.rules.aux.CherryPick.pickByOracle(CherryPick.scala:123)
	at at.forsyte.apalache.tla.bmcmt.rules.IfThenElseRule.iteGeneral(IfThenElseRule.scala:80)
	at at.forsyte.apalache.tla.bmcmt.rules.IfThenElseRule.apply(IfThenElseRule.scala:52)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.apply(LetInRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.IfThenElseRule.apply(IfThenElseRule.scala:41)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.bindOperator(LetInRule.scala:44)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.$anonfun$apply$1(LetInRule.scala:25)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.apply(LetInRule.scala:25)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.apply(LetInRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.apply(LetInRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.IfThenElseRule.apply(IfThenElseRule.scala:41)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.bindOperator(LetInRule.scala:44)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.$anonfun$apply$1(LetInRule.scala:25)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.apply(LetInRule.scala:25)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.apply(LetInRule.scala:26)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.bindOperator(LetInRule.scala:44)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.$anonfun$apply$1(LetInRule.scala:25)
	at scala.collection.LinearSeqOptimized.foldLeft(LinearSeqOptimized.scala:126)
	at scala.collection.LinearSeqOptimized.foldLeft$(LinearSeqOptimized.scala:122)
	at scala.collection.immutable.List.foldLeft(List.scala:91)
	at at.forsyte.apalache.tla.bmcmt.rules.LetInRule.apply(LetInRule.scala:25)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.mapArg$1(AndRule.scala:82)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.$anonfun$apply$2(AndRule.scala:86)
	at scala.collection.immutable.List.map(List.scala:297)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.apply(AndRule.scala:86)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.mapArg$1(AndRule.scala:82)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.$anonfun$apply$2(AndRule.scala:86)
	at scala.collection.immutable.List.map(List.scala:293)
	at at.forsyte.apalache.tla.bmcmt.rules.AndRule.apply(AndRule.scala:86)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteOnce(SymbStateRewriterImpl.scala:329)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.doRecursive$1(SymbStateRewriterImpl.scala:360)
	at at.forsyte.apalache.tla.bmcmt.SymbStateRewriterImpl.rewriteUntilDone(SymbStateRewriterImpl.scala:394)
	at at.forsyte.apalache.tla.bmcmt.trex.TransitionExecutorImpl.prepareTransition(TransitionExecutorImpl.scala:98)
	at at.forsyte.apalache.tla.bmcmt.trex.FilteredTransitionExecutor.prepareTransition(FilteredTransitionExecutor.scala:34)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5(SeqModelChecker.scala:112)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.$anonfun$prepareTransitionsAndCheckInvariants$5$adapted(SeqModelChecker.scala:106)
	at scala.collection.TraversableLike$WithFilter.$anonfun$foreach$1(TraversableLike.scala:924)
	at scala.collection.immutable.List.foreach(List.scala:431)
	at scala.collection.TraversableLike$WithFilter.foreach(TraversableLike.scala:923)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.prepareTransitionsAndCheckInvariants(SeqModelChecker.scala:106)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.makeStep(SeqModelChecker.scala:51)
	at at.forsyte.apalache.tla.bmcmt.SeqModelChecker.run(SeqModelChecker.scala:39)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.runIncrementalChecker(BoundedCheckerPassImpl.scala:120)
	at at.forsyte.apalache.tla.bmcmt.passes.BoundedCheckerPassImpl.execute(BoundedCheckerPassImpl.scala:87)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.exec$1(PassChainExecutor.scala:22)
	at at.forsyte.apalache.infra.passes.PassChainExecutor.run(PassChainExecutor.scala:37)
	at at.forsyte.apalache.tla.Tool$.runCheck(Tool.scala:175)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.$anonfun$run$2$adapted(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.handleExceptions(Tool.scala:260)
	at at.forsyte.apalache.tla.Tool$.run(Tool.scala:95)
	at at.forsyte.apalache.tla.Tool$.main(Tool.scala:45)
	at at.forsyte.apalache.tla.Tool.main(Tool.scala)
18:20:39.583 [main] INFO  a.f.a.t.Tool$ - It took me 0 days  0 hours  0 min  9 sec
18:20:39.584 [main] INFO  a.f.a.t.Tool$ - Total time: 9.599 sec

```
command line output:
```
Checker options: filename=IBCCore.tla, init=, next=, inv=         I@17:46:40.075
Tuning:                                                           I@17:46:40.363
PASS #0: SanyParser                                               I@17:46:40.363
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/IBCCore.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Integers.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/FiniteSets.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Sequences.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/IBCCoreDefinitions.tla
Parsing file /private/var/folders/r3/_hxg4k0x4sgf0vh4jkv91hvh0000gn/T/Naturals.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS18Relayer.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/Chain.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS02ClientHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS03ConnectionHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS04ChannelHandlers.tla
Parsing file /Users/ilina/repositories/informal/ibc-rs/docs/spec/tla/ibc-core/ICS04PacketHandlers.tla
PASS #1: TypeCheckerSnowcat                                       I@17:46:41.772
 > Running Snowcat .::.                                           I@17:46:41.772
 > Your types are great!                                          I@17:46:44.848
 > All expressions are typed                                      I@17:46:44.848
PASS #2: ConfigurationPass                                        I@17:46:45.192
  > IBCCore.cfg: Loading TLC configuration                        I@17:46:45.195
  > Using the init predicate Init from the TLC config             I@17:46:45.316
  > Using the next predicate Next from the TLC config             I@17:46:45.316
  > IBCCore.cfg: found INVARIANTS: TypeOK, IBCInv                 I@17:46:45.317
  > Set the initialization predicate to Init                      I@17:46:45.319
  > Set the transition predicate to Next                          I@17:46:45.320
  > Set an invariant to TypeOK                                    I@17:46:45.321
  > Set an invariant to IBCInv                                    I@17:46:45.322
  > Replaced CONSTANT PacketDatagramsRelayer1 with TRUE           I@17:46:45.324
  > Replaced CONSTANT PacketDatagramsRelayer2 with FALSE          I@17:46:45.325
  > Replaced CONSTANT MaxVersion with 1                           I@17:46:45.325
  > Replaced CONSTANT MaxPacketSeq with 1                         I@17:46:45.325
  > Replaced CONSTANT ChannelOrdering with "UNORDERED"            I@17:46:45.325
  > Replaced CONSTANT ClientDatagramsRelayer1 with TRUE           I@17:46:45.325
  > Replaced CONSTANT ClientDatagramsRelayer2 with FALSE          I@17:46:45.325
  > Replaced CONSTANT MaxHeight with 2                            I@17:46:45.326
  > Replaced CONSTANT ChannelDatagramsRelayer1 with TRUE          I@17:46:45.326
  > Replaced CONSTANT ChannelDatagramsRelayer2 with FALSE         I@17:46:45.326
  > Replaced CONSTANT ConnectionDatagramsRelayer1 with TRUE       I@17:46:45.326
  > Replaced CONSTANT ConnectionDatagramsRelayer2 with FALSE      I@17:46:45.326
PASS #3: DesugarerPass                                            I@17:46:45.532
  > Desugaring...                                                 I@17:46:45.532
PASS #4: UnrollPass                                               I@17:46:45.662
  > Unroller                                                      I@17:46:45.752
PASS #5: PrimingPass                                              I@17:46:46.261
  > Introducing InitPrimed for Init'                              I@17:46:46.265
PASS #6: CoverAnalysisPass                                        I@17:46:46.421
PASS #7: InlinePass                                               I@17:46:46.421
  > InlinerOfUserOper                                             I@17:46:46.422
  > LetInExpander                                                 I@17:46:46.625
  > InlinerOfUserOper                                             I@17:46:46.918
Leaving only relevant operators: CInitPrimed, IBCInv, Init, InitPrimed, Next, TypeOK I@17:46:46.953
PASS #8: VCGen                                                    I@17:46:47.030
  > Producing verification conditions from the invariant TypeOK   I@17:46:47.030
  > VCGen produced 20 verification condition(s)                   I@17:46:47.033
  > Producing verification conditions from the invariant IBCInv   I@17:46:47.036
  > VCGen produced 2 verification condition(s)                    I@17:46:47.037
PASS #9: PreprocessingPass                                        I@17:46:47.143
  > Before preprocessing: unique renaming                         I@17:46:47.143
 > Applying standard transformations:                             I@17:46:47.150
  > PrimePropagation                                              I@17:46:47.150
  > Desugarer                                                     I@17:46:47.290
  > UniqueRenamer                                                 I@17:46:47.508
  > Normalizer                                                    I@17:46:47.720
  > Keramelizer                                                   I@17:46:47.883
  > After preprocessing: UniqueRenamer                            I@17:46:48.117
PASS #10: TransitionFinderPass                                    I@17:46:48.403
  > Found 1 initializing transitions                              I@17:46:48.627
  > Found 22 transitions                                          I@17:46:48.852
  > No constant initializer                                       I@17:46:48.852
  > Applying unique renaming                                      I@17:46:48.853
PASS #11: OptimizationPass                                        I@17:46:49.050
 > Applying optimizations:                                        I@17:46:49.055
  > ConstSimplifier                                               I@17:46:49.056
  > ExprOptimizer                                                 I@17:46:49.131
  > ConstSimplifier                                               I@17:46:49.183
PASS #12: AnalysisPass                                            I@17:46:49.349
 > Marking skolemizable existentials and sets to be expanded...   I@17:46:49.351
  > SkolemizationMarker                                           I@17:46:49.352
  > ExpansionMarker                                               I@17:46:49.360
The set SUBSET (1 .. 1) will be expanded. This will blow up the solver. W@17:46:49.364
The set SUBSET (1 .. 1) will be expanded. This will blow up the solver. W@17:46:49.364
The set SUBSET (1 .. 1) will be expanded. This will blow up the solver. W@17:46:49.365
The set SUBSET (1 .. 1) will be expanded. This will blow up the solver. W@17:46:49.365
IBCCoreDefinitions.tla:323:32-323:66: unexpected expression: Seq({["sequence" ↦ t_pb$1, "timeoutHeight" ↦ t_pc$1, "srcPortID" ↦ t_pd$1, "srcChannelID" ↦ t_pe$1, "dstPortID" ↦ t_pf$1, "dstChannelID" ↦ t_pg$1] : t_pb$1 ∈ (1 .. 1), t_pc$1 ∈ (1 .. 2), t_pd$1 ∈ {"portA", "portB"}, t_pe$1 ∈ {"chanAtoB", "chanBtoA"}, t_pf$1 ∈ {"portA", "portB"}, t_pg$1 ∈ {"chanAtoB", "chanBtoA"}}) E@17:46:49.540
Unexpected expressions in the specification (see the error messages) E@17:46:49.541
It took me 0 days  0 hours  0 min  9 sec                          I@17:46:49.542
Total time: 9.471 sec                                             I@17:46:49.542
EXITCODE: ERROR (99)
```

## System information

- Apalache version: 0.15.2-SNAPSHOT build v0.15.1-4-gb68618c
- OS: Mac OS 11.2.3
- JDK version: Java SE Development Kit 1.8.0_261

### PR DESCRIPTION
**Pull request by konnov**
This PR fixes two bugs in the declaration sorter. Closes #758 and #645.

- [x] Tests added for any new code
- [x] Ran `make fmt-fix` (or had formatting run automatically on all files edited)
- [ ] ~Documentation added for any new functionality~
- [x] Entry added to [UNRELEASED.md](./UNRELEASED.md) for any new functionality

### CODE REVIEW

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala [hunk 1]
```diff
@@ -170,7 +170,7 @@ class EtcTypeChecker(varPool: TypeVarPool, inferPolytypes: Boolean = false) exte
           onTypeFound(name.sourceRef, nameType)
           computeRec(ctx, solver, mkApp(ex.sourceRef, Seq(nameType), args: _*))
         } else {
-          onTypeError(ex.sourceRef, s"Undefined operator name $name. Introduce a type annotation.")
+          onTypeError(ex.sourceRef, s"It looks like the operator $name is used before it is defined. Is it true?")
```
Comment (shonfeder) [inline tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:173]: I think this is too vague and uncertain. Can we just say:

```suggestion
          onTypeError(ex.sourceRef, s"The operator $name is used before it is defined.")
```

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala [hunk 2]
```diff
@@ -92,7 +92,7 @@ class EtcTypeChecker(varPool: TypeVarPool, inferPolytypes: Boolean = false) exte
             computeRec(ctx, solver, mkConst(ex.sourceRef, knownType))
           }
         } else {
-          onTypeError(ex.sourceRef, s"Undefined name $name. Introduce a type annotation.")
+          onTypeError(ex.sourceRef, s"Found no annotation for $name. Did you write one?")
```
Comment (shonfeder) [inline tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:95]:
```suggestion
          onTypeError(ex.sourceRef, s"No annotation found for $name.")
```

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala (hunk 1 above)
Comment (konnov) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:173]: Well, I softened it a bit, because there was a bug where apalache barked on the operator order, while the bug was in apalache :D

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala (hunk 2 above)
Comment (konnov) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:95]: I am trying to give the user an action hint about what to do instead of just displaying an error.

Comment (konnov) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:95]: I think we are not used to helpful communication with tools. Trying to make the error messages actionable :-)

Comment (shonfeder) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:95]: I think it's obvious that if an annotation is missing, the way to fix it is to supply an annotation. The rhetorical questions don't help with communication.

If you want to give a hint, imo it should be something like: "Ensure the variable `$name` is annotated. See <link to docs> for more on type annotations.". Maybe it's just me, but I find these rhetorical questions irritating.

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala (hunk 1 above)
Comment (shonfeder) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:173]: Errors happen. But I don't think it'll help the stability or usability of the tool in the long run if we phrase all the error messages tentatively in case we actually made a mistake in the implementation. It means we're optimizing for a pathological condition. IMO, if you really want to add a note communicating that we're not sure whether the implementation is correct in this error message, then you could just say that: "This detection may be in error. Please file an issue if you think it is." Or something more direct.

**Review by shonfeder — APPROVED** [review]
I'm approving, tho my opinion hasn't changed about the error messages. But not something I'd want to block on. :+1:

File: tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala (hunk 2 above)
Comment (konnov) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala:95]: I also find these questions annoying. But are we average users? :D

Comment (konnov) [reply tla-types/src/main/scala/at/forsyte/apalache/tla/typecheck/etc/EtcTypeChecker.scala]: I have changed to a less chatty message: "No annotation found for $name. Make sure that you've put one in front of $name."
